-- ============================================================
-- base_p0.sql — PostgreSQL
-- 通知相关独立表
-- ============================================================

CREATE TABLE base_notification_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    template_code varchar(50) NOT NULL,
    channel notify_channel NOT NULL,
    title_template varchar(200) NOT NULL,
    content_template text NOT NULL,
    category smallint,
    priority smallint DEFAULT 1,
    status smallint DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (template_code)
);

CREATE INDEX idx_base_notification_templates_code_channel ON base_notification_templates (template_code, channel);

CREATE TRIGGER trg_base_notification_templates_updated_at
    BEFORE UPDATE ON base_notification_templates
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE base_notification_templates IS '通知模板表';
COMMENT ON COLUMN base_notification_templates.template_code IS '模板代码（如 ORDER_PAID_SUCCESS）';
COMMENT ON COLUMN base_notification_templates.channel IS 'in_app-站内 push-Push sms-短信 email-邮件';
COMMENT ON COLUMN base_notification_templates.title_template IS '标题模板（支持变量 {{.OrderID}}）';
COMMENT ON COLUMN base_notification_templates.content_template IS '内容模板';
COMMENT ON COLUMN base_notification_templates.category IS '默认分类';
COMMENT ON COLUMN base_notification_templates.priority IS '默认优先级';
COMMENT ON COLUMN base_notification_templates.status IS '1-启用 0-停用';


CREATE TABLE base_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    title varchar(200) NOT NULL,
    content text NOT NULL,
    content_template varchar(100),
    template_params jsonb,
    channel notify_channel NOT NULL,
    category notify_category NOT NULL,
    target_type varchar(30),
    target_id bigint,
    redirect_url varchar(500),
    icon_url varchar(500),
    priority smallint DEFAULT 1,
    created_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_base_notifications_user_id ON base_notifications (user_id);
CREATE INDEX idx_base_notifications_merchant ON base_notifications (merchant_id);
CREATE INDEX idx_base_notifications_channel ON base_notifications (channel);
CREATE INDEX idx_base_notifications_category ON base_notifications (category);
CREATE INDEX idx_base_notifications_target ON base_notifications (target_type, target_id);
CREATE INDEX idx_base_notifications_created ON base_notifications (created_at);

CREATE TRIGGER trg_base_notifications_updated_at
    BEFORE UPDATE ON base_notifications
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE base_notifications IS '统一通知表';
COMMENT ON COLUMN base_notifications.user_id IS '0-全体用户 >0-指定用户';
COMMENT ON COLUMN base_notifications.merchant_id IS '所属商家ID（0表示平台）';
COMMENT ON COLUMN base_notifications.title IS '通知标题';
COMMENT ON COLUMN base_notifications.content IS '通知内容（最终渲染后的文本）';
COMMENT ON COLUMN base_notifications.content_template IS '内容模板ID（用于统计/调试）';
COMMENT ON COLUMN base_notifications.template_params IS '模板参数（存原始变量，便于回溯）';
COMMENT ON COLUMN base_notifications.channel IS 'in_app-站内消息 push-App Push sms-短信 email-邮件 wechat_template-微信模板消息';
COMMENT ON COLUMN base_notifications.category IS 'system-系统公告 order-订单通知 marketing-营销推广 interaction-互动通知 security-安全提醒';
COMMENT ON COLUMN base_notifications.target_type IS '关联业务类型: order/coupon/review/activity 等';
COMMENT ON COLUMN base_notifications.target_id IS '关联业务ID';
COMMENT ON COLUMN base_notifications.redirect_url IS '跳转链接（优先级高于 target_type+id）';
COMMENT ON COLUMN base_notifications.icon_url IS '通知图标（如订单图标、优惠券图标）';
COMMENT ON COLUMN base_notifications.priority IS '优先级: 0-高 1-中 2-低（用于排序展示）';
COMMENT ON COLUMN base_notifications.created_by IS '创建人（0表示系统自动）';


CREATE TABLE base_notification_reads (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    notification_id bigint NOT NULL,
    user_id bigint NOT NULL,
    read_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (notification_id, user_id)
);

CREATE INDEX idx_base_notification_reads_user ON base_notification_reads (user_id);

COMMENT ON TABLE base_notification_reads IS '通知已读记录表';
COMMENT ON COLUMN base_notification_reads.notification_id IS '关联通知ID';
COMMENT ON COLUMN base_notification_reads.user_id IS '用户ID';
COMMENT ON COLUMN base_notification_reads.read_at IS '阅读时间';
