-- ============================================================
-- mch_p2.sql — PostgreSQL
-- 商户结算明细（依赖 P1: settlement_logs）
-- ============================================================

CREATE TABLE mch_settlement_details (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    order_id bigint NOT NULL,
    settlement_log_id bigint NOT NULL,
    order_amount bigint NOT NULL DEFAULT 0,
    commission_amount bigint NOT NULL DEFAULT 0,
    settlement_amount bigint NOT NULL DEFAULT 0,
    refund_amount bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_mch_settlement_details_merchant_order ON mch_settlement_details (merchant_id, order_id);
CREATE INDEX idx_mch_settlement_details_settlement_log ON mch_settlement_details (settlement_log_id)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_mch_settlement_details_updated_at
    BEFORE UPDATE ON mch_settlement_details
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_settlement_details IS '商家结算明细表';
COMMENT ON COLUMN mch_settlement_details.merchant_id IS '商家ID';
COMMENT ON COLUMN mch_settlement_details.order_id IS '订单ID';
COMMENT ON COLUMN mch_settlement_details.settlement_log_id IS '结算流水ID';
COMMENT ON COLUMN mch_settlement_details.order_amount IS '订单实付金额（分）';
COMMENT ON COLUMN mch_settlement_details.commission_amount IS '平台佣金（分）';
COMMENT ON COLUMN mch_settlement_details.settlement_amount IS '应结算金额（分）';
COMMENT ON COLUMN mch_settlement_details.refund_amount IS '退款冲减金额（分）';
COMMENT ON COLUMN mch_settlement_details.status IS '0-待结算 1-已结算 2-已冲减';
