-- ============================================================
-- mch_p1.sql — PostgreSQL
-- 商户运营相关表（依赖 P0: mch_merchants）
-- ============================================================

CREATE TABLE mch_merchant_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    role_id bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    invited_at timestamp(3) DEFAULT NULL,
    last_login_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (merchant_id, staff_id)
);

CREATE INDEX idx_mch_merchant_users_merchant_status ON mch_merchant_users (merchant_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_mch_merchant_users_staff_id ON mch_merchant_users (staff_id)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_mch_merchant_users_updated_at
    BEFORE UPDATE ON mch_merchant_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_users IS '商家-员工关联表（B端员工通过此表绑定商户）';
COMMENT ON COLUMN mch_merchant_users.staff_id IS '员工ID（关联 sys_staff.id）';
COMMENT ON COLUMN mch_merchant_users.role_id IS '商家角色ID（关联 mch_merchant_roles.id，与平台RBAC隔离）';
COMMENT ON COLUMN mch_merchant_users.status IS '1-正常 2-禁用';
COMMENT ON COLUMN mch_merchant_users.invited_at IS '邀请时间';
COMMENT ON COLUMN mch_merchant_users.last_login_at IS '最后登录时间';


CREATE TABLE mch_merchant_balances (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    available_balance bigint NOT NULL DEFAULT 0,
    freeze_balance bigint NOT NULL DEFAULT 0,
    currency varchar(10) NOT NULL DEFAULT 'CNY',
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (merchant_id, currency)
);

CREATE INDEX idx_mch_merchant_balances_active ON mch_merchant_balances (merchant_id)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_mch_merchant_balances_updated_at
    BEFORE UPDATE ON mch_merchant_balances
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_balances IS '商家资金余额表';
COMMENT ON COLUMN mch_merchant_balances.available_balance IS '可提现余额（分）';
COMMENT ON COLUMN mch_merchant_balances.freeze_balance IS '冻结余额（分）';
COMMENT ON COLUMN mch_merchant_balances.currency IS '币种';
COMMENT ON COLUMN mch_merchant_balances.version IS '版本号（并发控制）';


CREATE TABLE mch_merchant_withdrawals (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    withdraw_no varchar(32) NOT NULL,
    amount bigint NOT NULL,
    bank_account_id bigint NOT NULL,
    status smallint NOT NULL DEFAULT 0,
    audit_remark varchar(200) DEFAULT '',
    applied_at timestamp(3) DEFAULT NULL,
    approved_at timestamp(3) DEFAULT NULL,
    paid_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (withdraw_no)
);

CREATE INDEX idx_mch_merchant_withdrawals_merchant_status ON mch_merchant_withdrawals (merchant_id, status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_mch_merchant_withdrawals_updated_at
    BEFORE UPDATE ON mch_merchant_withdrawals
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_withdrawals IS '商家提现申请表';
COMMENT ON COLUMN mch_merchant_withdrawals.withdraw_no IS '提现单号';
COMMENT ON COLUMN mch_merchant_withdrawals.amount IS '提现金额（分）';
COMMENT ON COLUMN mch_merchant_withdrawals.bank_account_id IS '结算账户ID';
COMMENT ON COLUMN mch_merchant_withdrawals.status IS '0-待审核 1-审核通过 2-已打款 3-拒绝';
COMMENT ON COLUMN mch_merchant_withdrawals.audit_remark IS '审批备注';
COMMENT ON COLUMN mch_merchant_withdrawals.applied_at IS '申请时间';
COMMENT ON COLUMN mch_merchant_withdrawals.approved_at IS '审批时间';
COMMENT ON COLUMN mch_merchant_withdrawals.paid_at IS '打款时间';


CREATE TABLE mch_merchant_settlement_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    settlement_no varchar(32) NOT NULL,
    settlement_cycle varchar(20),
    total_amount bigint NOT NULL DEFAULT 0,
    commission_amount bigint NOT NULL DEFAULT 0,
    settlement_amount bigint NOT NULL DEFAULT 0,
    status smallint DEFAULT 0,
    settled_at timestamp(3),
    paid_at timestamp(3),
    remark varchar(500),
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (settlement_no)
);

CREATE INDEX idx_mch_merchant_settlement_logs_merchant ON mch_merchant_settlement_logs (merchant_id);
CREATE INDEX idx_mch_merchant_settlement_logs_status ON mch_merchant_settlement_logs (status);
CREATE INDEX idx_mch_merchant_settlement_logs_active ON mch_merchant_settlement_logs (merchant_id, status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_mch_merchant_settlement_logs_updated_at
    BEFORE UPDATE ON mch_merchant_settlement_logs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_settlement_logs IS '商家结算流水表';
COMMENT ON COLUMN mch_merchant_settlement_logs.settlement_no IS '结算单号';
COMMENT ON COLUMN mch_merchant_settlement_logs.settlement_cycle IS '结算周期（如 2026-07-01~2026-07-15）';
COMMENT ON COLUMN mch_merchant_settlement_logs.total_amount IS '期内总金额（分）';
COMMENT ON COLUMN mch_merchant_settlement_logs.commission_amount IS '平台佣金（分）';
COMMENT ON COLUMN mch_merchant_settlement_logs.settlement_amount IS '应结算金额（分）';
COMMENT ON COLUMN mch_merchant_settlement_logs.status IS '0-待结算 1-已结算 2-已打款';
COMMENT ON COLUMN mch_merchant_settlement_logs.settled_at IS '结算时间';
COMMENT ON COLUMN mch_merchant_settlement_logs.paid_at IS '打款时间';
COMMENT ON COLUMN mch_merchant_settlement_logs.remark IS '备注';


CREATE TABLE mch_merchant_role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    role_id bigint NOT NULL,
    permission_name varchar(100) NOT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (role_id, permission_name)
);

CREATE INDEX idx_mch_merchant_role_permissions_merchant ON mch_merchant_role_permissions (merchant_id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_mch_merchant_role_permissions_permission ON mch_merchant_role_permissions (permission_name);

COMMENT ON TABLE mch_merchant_role_permissions IS '商家角色-权限关联表（基于平台权限标识）';
COMMENT ON COLUMN mch_merchant_role_permissions.role_id IS '角色ID（关联 mch_merchant_roles.id）';
COMMENT ON COLUMN mch_merchant_role_permissions.permission_name IS '权限标识（对应 sys_permissions.name）';
