-- ============================================================
-- mch_p0.sql — PostgreSQL
-- 商户域基础表
-- ============================================================

CREATE TABLE mch_merchants (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_name varchar(100) NOT NULL,
    merchant_code varchar(50) NOT NULL,
    merchant_type smallint DEFAULT 1,
    merchant_level smallint DEFAULT 1,
    business_scope varchar(200),
    business_years int DEFAULT 0,
    contact_person varchar(50),
    contact_phone varchar(20),
    contact_email varchar(100),
    logo_url varchar(500),
    banner_url varchar(500),
    shop_description text,
    status smallint DEFAULT 0,
    audit_status smallint DEFAULT 0,
    audit_reason varchar(200),
    audited_at timestamp(3),
    frozen_reason varchar(200),
    commission_rate bigint NOT NULL DEFAULT 0,
    settlement_cycle smallint DEFAULT 1,
    total_orders int DEFAULT 0,
    total_sales bigint NOT NULL DEFAULT 0,
    avg_rating decimal(2,1) DEFAULT 0.0,
    product_count int DEFAULT 0,
    settled_at timestamp(3),
    expire_at timestamp(3),
    created_by bigint,
    updated_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (merchant_code)
);

CREATE INDEX idx_mch_merchants_name ON mch_merchants (merchant_name);
CREATE INDEX idx_mch_merchants_code ON mch_merchants (merchant_code);
CREATE INDEX idx_mch_merchants_status_level ON mch_merchants (status, merchant_level);
CREATE INDEX idx_mch_merchants_settled ON mch_merchants (settled_at);

CREATE TRIGGER trg_mch_merchants_updated_at
    BEFORE UPDATE ON mch_merchants
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchants IS '商家主表';
COMMENT ON COLUMN mch_merchants.merchant_name IS '商家名称（店铺名）';
COMMENT ON COLUMN mch_merchants.merchant_code IS '商家编码（系统生成，唯一）';
COMMENT ON COLUMN mch_merchants.merchant_type IS '1-个人商家 2-企业商家 3-品牌直营';
COMMENT ON COLUMN mch_merchants.merchant_level IS '商家等级 1-普通 2-银牌 3-金牌 4-钻石（影响佣金率/权限）';
COMMENT ON COLUMN mch_merchants.business_scope IS '经营范围';
COMMENT ON COLUMN mch_merchants.business_years IS '经营年限（入驻年限）';
COMMENT ON COLUMN mch_merchants.contact_person IS '主要联系人';
COMMENT ON COLUMN mch_merchants.contact_phone IS '联系电话';
COMMENT ON COLUMN mch_merchants.contact_email IS '联系邮箱';
COMMENT ON COLUMN mch_merchants.logo_url IS '店铺Logo';
COMMENT ON COLUMN mch_merchants.banner_url IS '店铺Banner图';
COMMENT ON COLUMN mch_merchants.shop_description IS '店铺简介';
COMMENT ON COLUMN mch_merchants.status IS '0-待审核 1-正常 2-冻结 3-已注销';
COMMENT ON COLUMN mch_merchants.audit_status IS '0-待审核 1-审核通过 2-审核拒绝';
COMMENT ON COLUMN mch_merchants.audit_reason IS '审核拒绝原因';
COMMENT ON COLUMN mch_merchants.frozen_reason IS '冻结原因';
COMMENT ON COLUMN mch_merchants.commission_rate IS '平台抽佣比例（千分比，如 50 表示5%）';
COMMENT ON COLUMN mch_merchants.settlement_cycle IS '结算周期 1-T+1 2-T+7 3-月结';
COMMENT ON COLUMN mch_merchants.total_orders IS '历史总订单数';
COMMENT ON COLUMN mch_merchants.total_sales IS '历史总销售额（分）';
COMMENT ON COLUMN mch_merchants.avg_rating IS '店铺平均评分';
COMMENT ON COLUMN mch_merchants.product_count IS '在售商品数量';
COMMENT ON COLUMN mch_merchants.settled_at IS '入驻时间';
COMMENT ON COLUMN mch_merchants.expire_at IS '合同到期时间';
COMMENT ON COLUMN mch_merchants.created_by IS '创建人';
COMMENT ON COLUMN mch_merchants.updated_by IS '更新人';


CREATE TABLE mch_merchant_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    contact_name varchar(50) NOT NULL,
    contact_phone varchar(20) NOT NULL,
    contact_role varchar(30),
    is_primary smallint DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_mch_merchant_contacts_merchant ON mch_merchant_contacts (merchant_id);
CREATE INDEX idx_mch_merchant_contacts_deleted_at ON mch_merchant_contacts (deleted_at);

CREATE TRIGGER trg_mch_merchant_contacts_updated_at
    BEFORE UPDATE ON mch_merchant_contacts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_contacts IS '商家联系人表';
COMMENT ON COLUMN mch_merchant_contacts.contact_name IS '联系人姓名';
COMMENT ON COLUMN mch_merchant_contacts.contact_phone IS '联系电话';
COMMENT ON COLUMN mch_merchant_contacts.contact_role IS '联系人角色：finance-财务 legal-法人 operation-运营';
COMMENT ON COLUMN mch_merchant_contacts.is_primary IS '是否主要联系人 0-否 1-是';


CREATE TABLE mch_merchant_bank_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    bank_name varchar(100) NOT NULL,
    bank_branch varchar(100),
    account_name varchar(100) NOT NULL,
    account_no varchar(50) NOT NULL,
    account_type smallint DEFAULT 1,
    is_default smallint DEFAULT NULL,
    status smallint DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (merchant_id, is_default)
);

CREATE INDEX idx_mch_merchant_bank_accounts_merchant ON mch_merchant_bank_accounts (merchant_id);
CREATE INDEX idx_mch_merchant_bank_accounts_deleted_at ON mch_merchant_bank_accounts (deleted_at);

CREATE TRIGGER trg_mch_merchant_bank_accounts_updated_at
    BEFORE UPDATE ON mch_merchant_bank_accounts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_bank_accounts IS '商家结算银行账户表';
COMMENT ON COLUMN mch_merchant_bank_accounts.bank_name IS '开户行';
COMMENT ON COLUMN mch_merchant_bank_accounts.bank_branch IS '开户支行';
COMMENT ON COLUMN mch_merchant_bank_accounts.account_name IS '开户名';
COMMENT ON COLUMN mch_merchant_bank_accounts.account_no IS '银行账号';
COMMENT ON COLUMN mch_merchant_bank_accounts.account_type IS '1-对公账户 2-对私账户';
COMMENT ON COLUMN mch_merchant_bank_accounts.is_default IS '是否默认结算账户（NULL=非默认, 1=默认）';
COMMENT ON COLUMN mch_merchant_bank_accounts.status IS '1-正常 2-禁用';


CREATE TABLE mch_merchant_qualifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    qualification_type varchar(50) NOT NULL,
    qualification_name varchar(200) NOT NULL,
    file_url varchar(500) NOT NULL,
    expire_at timestamp(3),
    status smallint DEFAULT 0,
    audit_remark varchar(200),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_mch_merchant_qualifications_merchant ON mch_merchant_qualifications (merchant_id);
CREATE INDEX idx_mch_merchant_qualifications_expire ON mch_merchant_qualifications (expire_at);
CREATE INDEX idx_mch_merchant_qualifications_deleted_at ON mch_merchant_qualifications (deleted_at);

CREATE TRIGGER trg_mch_merchant_qualifications_updated_at
    BEFORE UPDATE ON mch_merchant_qualifications
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_qualifications IS '商家资质表';
COMMENT ON COLUMN mch_merchant_qualifications.qualification_type IS '资质类型：business_license-营业执照 food-食品经营许可 brand_authorization-品牌授权';
COMMENT ON COLUMN mch_merchant_qualifications.qualification_name IS '资质名称';
COMMENT ON COLUMN mch_merchant_qualifications.file_url IS '资质文件URL';
COMMENT ON COLUMN mch_merchant_qualifications.expire_at IS '有效期';
COMMENT ON COLUMN mch_merchant_qualifications.status IS '0-待审核 1-审核通过 2-已过期 3-审核拒绝';
COMMENT ON COLUMN mch_merchant_qualifications.audit_remark IS '审核备注';


CREATE TABLE mch_merchant_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    name varchar(50) NOT NULL,
    display_name varchar(100) NOT NULL DEFAULT '',
    description varchar(255) NOT NULL DEFAULT '',
    role_type varchar(20) NOT NULL DEFAULT 'custom',
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_mch_merchant_roles_merchant ON mch_merchant_roles (merchant_id);
CREATE INDEX idx_mch_merchant_roles_type ON mch_merchant_roles (role_type);
CREATE INDEX idx_mch_merchant_roles_status ON mch_merchant_roles (status);
CREATE INDEX idx_mch_merchant_roles_deleted_at ON mch_merchant_roles (deleted_at);

CREATE TRIGGER trg_mch_merchant_roles_updated_at
    BEFORE UPDATE ON mch_merchant_roles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mch_merchant_roles IS '商家角色定义表（与平台RBAC隔离）';
COMMENT ON COLUMN mch_merchant_roles.merchant_id IS '商家ID（0=平台预置角色）';
COMMENT ON COLUMN mch_merchant_roles.name IS '角色名称（如店长/运营/财务）';
COMMENT ON COLUMN mch_merchant_roles.display_name IS '角色显示名称';
COMMENT ON COLUMN mch_merchant_roles.description IS '角色描述';
COMMENT ON COLUMN mch_merchant_roles.role_type IS 'builtin-系统预置 custom-商家自定义';
COMMENT ON COLUMN mch_merchant_roles.sort_order IS '排序值';
COMMENT ON COLUMN mch_merchant_roles.status IS '1-启用 0-禁用';
