-- ============================================================
-- mkt_p0.sql — PostgreSQL
-- 营销域核心表
-- ============================================================

CREATE TABLE mkt_promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_no varchar(32) NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    promo_name varchar(100) NOT NULL,
    promo_type smallint NOT NULL,
    promo_code varchar(50) DEFAULT '',
    start_time timestamp(3) NOT NULL,
    end_time timestamp(3) NOT NULL,
    total_quantity int DEFAULT 0,
    per_user_limit int DEFAULT 1,
    used_quantity int DEFAULT 0,
    rule_id bigint NOT NULL DEFAULT 0,
    status smallint DEFAULT 1,
    priority int DEFAULT 0,
    created_by bigint,
    updated_by bigint,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (promotion_no),
    UNIQUE (merchant_id, promo_code)
);

CREATE INDEX idx_mkt_promotions_merchant_status_time ON mkt_promotions (merchant_id, status, start_time, end_time);
CREATE INDEX idx_mkt_promotions_type_status ON mkt_promotions (promo_type, status);
CREATE INDEX idx_mkt_promotions_rule_id ON mkt_promotions (rule_id);

CREATE TRIGGER trg_mkt_promotions_updated_at
    BEFORE UPDATE ON mkt_promotions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mkt_promotions IS '统一促销活动表';
COMMENT ON COLUMN mkt_promotions.promotion_no IS '促销业务编号';
COMMENT ON COLUMN mkt_promotions.merchant_id IS '所属商家ID（0表示平台级活动）';
COMMENT ON COLUMN mkt_promotions.promo_name IS '活动名称';
COMMENT ON COLUMN mkt_promotions.promo_type IS '1-满减券 2-折扣券 3-秒杀 4-满额减 5-满件折 6-会员价';
COMMENT ON COLUMN mkt_promotions.promo_code IS '优惠码（优惠券专用）';
COMMENT ON COLUMN mkt_promotions.start_time IS '开始时间';
COMMENT ON COLUMN mkt_promotions.end_time IS '结束时间';
COMMENT ON COLUMN mkt_promotions.total_quantity IS '发行总量（0表示不限）';
COMMENT ON COLUMN mkt_promotions.per_user_limit IS '每人限领/限购数量';
COMMENT ON COLUMN mkt_promotions.used_quantity IS '已使用/已售数量（异步统计，非实时）';
COMMENT ON COLUMN mkt_promotions.rule_id IS '关联规则表ID';
COMMENT ON COLUMN mkt_promotions.status IS '1-草稿 2-待生效 3-生效中 4-已暂停 5-已结束 6-已作废';
COMMENT ON COLUMN mkt_promotions.priority IS '优先级（数字越大越优先，同类型互斥）';
COMMENT ON COLUMN mkt_promotions.created_by IS '创建人';
COMMENT ON COLUMN mkt_promotions.updated_by IS '更新人';
