-- ============================================================
-- mkt_p1.sql — PostgreSQL
-- 营销关联表（依赖 P0: promotions）
-- ============================================================

CREATE TABLE mkt_promotion_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    rule_name varchar(100),
    condition_type smallint NOT NULL,
    condition_value bigint NOT NULL DEFAULT 0,
    benefit_config jsonb NOT NULL,
    is_stackable smallint DEFAULT 0,
    stack_group int DEFAULT 0,
    created_by bigint,
    updated_by bigint,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_mkt_promotion_rules_promotion ON mkt_promotion_rules (promotion_id);
CREATE INDEX idx_mkt_promotion_rules_stack_group ON mkt_promotion_rules (stack_group, is_stackable);

CREATE TRIGGER trg_mkt_promotion_rules_updated_at
    BEFORE UPDATE ON mkt_promotion_rules
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mkt_promotion_rules IS '促销规则表（配置化）';
COMMENT ON COLUMN mkt_promotion_rules.promotion_id IS '所属促销ID';
COMMENT ON COLUMN mkt_promotion_rules.merchant_id IS '所属商家ID';
COMMENT ON COLUMN mkt_promotion_rules.rule_name IS '规则名称';
COMMENT ON COLUMN mkt_promotion_rules.condition_type IS '1-无门槛 2-满金额 3-满件数 4-指定用户等级';
COMMENT ON COLUMN mkt_promotion_rules.condition_value IS '门槛值（分）';
COMMENT ON COLUMN mkt_promotion_rules.benefit_config IS '优惠配置JSON。例：{"type":1,"value":3000} 或 {"type":2,"steps":...}';
COMMENT ON COLUMN mkt_promotion_rules.is_stackable IS '是否可与其他促销叠加 0-否 1-是';
COMMENT ON COLUMN mkt_promotion_rules.stack_group IS '叠加组ID（同组内互斥，不同组可叠加）';
COMMENT ON COLUMN mkt_promotion_rules.created_by IS '创建人';
COMMENT ON COLUMN mkt_promotion_rules.updated_by IS '更新人';


CREATE TABLE mkt_promotion_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    product_type smallint NOT NULL,
    target_id bigint,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (promotion_id, product_type, target_id)
);

CREATE INDEX idx_mkt_promotion_products_target ON mkt_promotion_products (target_id, product_type);

COMMENT ON TABLE mkt_promotion_products IS '促销适用商品表';
COMMENT ON COLUMN mkt_promotion_products.promotion_id IS '促销ID';
COMMENT ON COLUMN mkt_promotion_products.merchant_id IS '所属商家ID';
COMMENT ON COLUMN mkt_promotion_products.product_type IS '1-全站 2-指定分类 3-指定SPU 4-指定SKU';
COMMENT ON COLUMN mkt_promotion_products.target_id IS '目标ID（SPU_ID或SKU_ID或Category_ID）';


CREATE TABLE mkt_user_promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_promotion_no varchar(32) NOT NULL,
    user_id bigint NOT NULL,
    promotion_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    acquire_time timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    expire_time timestamp(3),
    status smallint DEFAULT 1,
    lock_order_id bigint DEFAULT NULL,
    used_time timestamp(3),
    order_id bigint,
    queue_token varchar(64) DEFAULT '',
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_promotion_no)
);

CREATE INDEX idx_mkt_user_promotions_user_available ON mkt_user_promotions (user_id, status, expire_time);
CREATE INDEX idx_mkt_user_promotions_promotion ON mkt_user_promotions (promotion_id);
CREATE INDEX idx_mkt_user_promotions_lock_order ON mkt_user_promotions (lock_order_id);
CREATE INDEX idx_mkt_user_promotions_order ON mkt_user_promotions (order_id);

CREATE TRIGGER trg_mkt_user_promotions_updated_at
    BEFORE UPDATE ON mkt_user_promotions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mkt_user_promotions IS '用户促销资产表（状态机优化）';
COMMENT ON COLUMN mkt_user_promotions.user_promotion_no IS '用户促销资产编号';
COMMENT ON COLUMN mkt_user_promotions.user_id IS '用户ID';
COMMENT ON COLUMN mkt_user_promotions.promotion_id IS '促销ID';
COMMENT ON COLUMN mkt_user_promotions.merchant_id IS '所属商家ID';
COMMENT ON COLUMN mkt_user_promotions.acquire_time IS '领取时间';
COMMENT ON COLUMN mkt_user_promotions.expire_time IS '过期时间';
COMMENT ON COLUMN mkt_user_promotions.status IS '1-未使用 2-锁定中(下单未付) 3-已使用 4-已过期 5-已作废';
COMMENT ON COLUMN mkt_user_promotions.lock_order_id IS '锁定的订单ID（用于回滚）';
COMMENT ON COLUMN mkt_user_promotions.used_time IS '使用时间';
COMMENT ON COLUMN mkt_user_promotions.order_id IS '最终使用的订单ID';
COMMENT ON COLUMN mkt_user_promotions.queue_token IS '秒杀排队令牌';


CREATE TABLE mkt_promotion_stocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_id bigint NOT NULL,
    sku_id bigint DEFAULT NULL,
    total_stock int NOT NULL DEFAULT 0,
    available_stock int NOT NULL DEFAULT 0,
    locked_stock int NOT NULL DEFAULT 0,
    version int NOT NULL DEFAULT 0,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (promotion_id, sku_id),
    CONSTRAINT chk_stock_positive CHECK (available_stock >= 0 AND locked_stock >= 0)
);

CREATE TRIGGER trg_mkt_promotion_stocks_updated_at
    BEFORE UPDATE ON mkt_promotion_stocks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE mkt_promotion_stocks IS '促销库存表（支持秒杀）';
COMMENT ON COLUMN mkt_promotion_stocks.promotion_id IS '促销ID';
COMMENT ON COLUMN mkt_promotion_stocks.sku_id IS 'SKU ID（秒杀专用，通用活动可为空）';
COMMENT ON COLUMN mkt_promotion_stocks.total_stock IS '总库存';
COMMENT ON COLUMN mkt_promotion_stocks.available_stock IS '可用库存';
COMMENT ON COLUMN mkt_promotion_stocks.locked_stock IS '锁定库存（下单未付）';
COMMENT ON COLUMN mkt_promotion_stocks.version IS '乐观锁版本号';


CREATE TABLE mkt_promotion_usage_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_id bigint NOT NULL,
    user_promotion_id bigint DEFAULT NULL,
    user_id bigint NOT NULL,
    order_id bigint NOT NULL,
    discount_amount bigint NOT NULL DEFAULT 0,
    promotion_snapshot jsonb DEFAULT NULL,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_mkt_promotion_usage_logs_order ON mkt_promotion_usage_logs (order_id);
CREATE INDEX idx_mkt_promotion_usage_logs_promotion_created ON mkt_promotion_usage_logs (promotion_id, created_at);
CREATE INDEX idx_mkt_promotion_usage_logs_user_created ON mkt_promotion_usage_logs (user_id, created_at);

COMMENT ON TABLE mkt_promotion_usage_logs IS '促销使用记录表（建议按 created_at 月度分区）';
COMMENT ON COLUMN mkt_promotion_usage_logs.promotion_id IS '促销ID';
COMMENT ON COLUMN mkt_promotion_usage_logs.user_promotion_id IS '用户促销资产ID';
COMMENT ON COLUMN mkt_promotion_usage_logs.user_id IS '用户ID';
COMMENT ON COLUMN mkt_promotion_usage_logs.order_id IS '使用的订单ID';
COMMENT ON COLUMN mkt_promotion_usage_logs.discount_amount IS '优惠金额（分）';
COMMENT ON COLUMN mkt_promotion_usage_logs.promotion_snapshot IS '优惠快照（名称、规则等）';
