-- ============================================================
-- rev_p0.sql — PostgreSQL
-- 评价域核心表
-- ============================================================

CREATE TABLE rev_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    review_no varchar(32) NOT NULL,
    user_id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    spu_id bigint NOT NULL,
    sku_id bigint DEFAULT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    overall_rating rating_score NOT NULL,
    quality_rating rating_score DEFAULT NULL,
    logistics_rating rating_score DEFAULT NULL,
    service_rating rating_score DEFAULT NULL,
    content text DEFAULT NULL,
    content_length smallint DEFAULT 0,
    is_anonymous smallint DEFAULT 0,
    has_media smallint DEFAULT 0,
    status review_status DEFAULT 'pending',
    risk_level smallint DEFAULT 0,
    reject_reason varchar(200) DEFAULT NULL,
    audited_by bigint DEFAULT NULL,
    audited_at timestamp(3) DEFAULT NULL,
    like_count int DEFAULT 0,
    helpful_count int DEFAULT 0,
    reply_count int DEFAULT 0,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (review_no),
    UNIQUE (order_item_id)
);

CREATE INDEX idx_rev_reviews_spu_status_created ON rev_reviews (spu_id, status, created_at);
CREATE INDEX idx_rev_reviews_merchant_status ON rev_reviews (merchant_id, status);
CREATE INDEX idx_rev_reviews_user_created ON rev_reviews (user_id, created_at);
CREATE INDEX idx_rev_reviews_rating_status ON rev_reviews (overall_rating, status);
CREATE INDEX idx_rev_reviews_audited ON rev_reviews (audited_at, status);

CREATE TRIGGER trg_rev_reviews_updated_at
    BEFORE UPDATE ON rev_reviews
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE rev_reviews IS '评价主表';
COMMENT ON COLUMN rev_reviews.review_no IS '评价业务单号（幂等键）';
COMMENT ON COLUMN rev_reviews.user_id IS '用户ID';
COMMENT ON COLUMN rev_reviews.order_id IS '订单ID（校验必须已购）';
COMMENT ON COLUMN rev_reviews.order_item_id IS '订单明细ID（用于区分同订单多商品）';
COMMENT ON COLUMN rev_reviews.spu_id IS '商品SPU ID';
COMMENT ON COLUMN rev_reviews.sku_id IS '商品SKU ID';
COMMENT ON COLUMN rev_reviews.merchant_id IS '所属商家ID';
COMMENT ON COLUMN rev_reviews.overall_rating IS '总体评分（1-5星）';
COMMENT ON COLUMN rev_reviews.quality_rating IS '质量评分';
COMMENT ON COLUMN rev_reviews.logistics_rating IS '物流评分';
COMMENT ON COLUMN rev_reviews.service_rating IS '服务评分';
COMMENT ON COLUMN rev_reviews.content IS '评价文字内容';
COMMENT ON COLUMN rev_reviews.content_length IS '内容长度（冗余，用于筛选优质评价）';
COMMENT ON COLUMN rev_reviews.is_anonymous IS '是否匿名 0-否 1-是';
COMMENT ON COLUMN rev_reviews.has_media IS '是否包含媒体 0-否 1-是';
COMMENT ON COLUMN rev_reviews.status IS 'pending-待审核 approved-审核通过 rejected-审核拒绝 user_deleted-用户删除 platform_hidden-平台屏蔽';
COMMENT ON COLUMN rev_reviews.risk_level IS '风险等级 0-正常 1-低风险 2-高风险';
COMMENT ON COLUMN rev_reviews.reject_reason IS '拒绝原因';
COMMENT ON COLUMN rev_reviews.audited_by IS '审核人ID';
COMMENT ON COLUMN rev_reviews.audited_at IS '审核时间';
COMMENT ON COLUMN rev_reviews.like_count IS '点赞数（异步校准）';
COMMENT ON COLUMN rev_reviews.helpful_count IS '有用数（异步校准）';
COMMENT ON COLUMN rev_reviews.reply_count IS '回复总数（异步校准）';
