-- ============================================================
-- rev_p1.sql — PostgreSQL
-- 评价关联表（依赖 P0: reviews）
-- ============================================================

CREATE TABLE rev_review_media (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    review_id bigint NOT NULL,
    media_type smallint DEFAULT 1,
    media_url varchar(500) NOT NULL,
    file_size int DEFAULT 0,
    width int DEFAULT 0,
    height int DEFAULT 0,
    duration int DEFAULT 0,
    sort_order int DEFAULT 0,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_rev_review_media_review_sort ON rev_review_media (review_id, sort_order);

COMMENT ON TABLE rev_review_media IS '评价媒体表';
COMMENT ON COLUMN rev_review_media.review_id IS '关联评价ID';
COMMENT ON COLUMN rev_review_media.media_type IS '1-图片 2-视频';
COMMENT ON COLUMN rev_review_media.media_url IS '媒体文件URL';
COMMENT ON COLUMN rev_review_media.file_size IS '文件大小（字节）';
COMMENT ON COLUMN rev_review_media.width IS '宽度（图片/视频）';
COMMENT ON COLUMN rev_review_media.height IS '高度（图片/视频）';
COMMENT ON COLUMN rev_review_media.duration IS '时长（视频，秒）';
COMMENT ON COLUMN rev_review_media.sort_order IS '排序';


CREATE TABLE rev_review_replies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    review_id bigint NOT NULL,
    root_reply_id bigint DEFAULT NULL,
    parent_id bigint DEFAULT NULL,
    reply_type smallint DEFAULT 1,
    content text NOT NULL,
    operator_id bigint DEFAULT NULL,
    operator_name varchar(50) DEFAULT '',
    status smallint DEFAULT 1,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_rev_review_replies_review_root ON rev_review_replies (review_id, root_reply_id, created_at);
CREATE INDEX idx_rev_review_replies_parent ON rev_review_replies (parent_id, created_at);

CREATE TRIGGER trg_rev_review_replies_updated_at
    BEFORE UPDATE ON rev_review_replies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE rev_review_replies IS '评价回复表（支持二级回复）';
COMMENT ON COLUMN rev_review_replies.review_id IS '关联评价ID';
COMMENT ON COLUMN rev_review_replies.root_reply_id IS '根回复ID（一级回复为NULL）';
COMMENT ON COLUMN rev_review_replies.parent_id IS '父级回复ID（支持二级回复）';
COMMENT ON COLUMN rev_review_replies.reply_type IS '1-商家回复 2-用户追问 3-平台回复';
COMMENT ON COLUMN rev_review_replies.content IS '回复内容';
COMMENT ON COLUMN rev_review_replies.operator_id IS '操作人ID';
COMMENT ON COLUMN rev_review_replies.operator_name IS '操作人名称（冗余，避免JOIN用户表）';
COMMENT ON COLUMN rev_review_replies.status IS '1-正常 2-隐藏 3-删除';


CREATE TABLE rev_review_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    review_id bigint NOT NULL,
    action varchar(30) NOT NULL,
    operator_id bigint DEFAULT NULL,
    operator_name varchar(50) DEFAULT '',
    before_status smallint DEFAULT NULL,
    after_status smallint DEFAULT NULL,
    remark varchar(200) DEFAULT NULL,
    snapshot jsonb DEFAULT NULL,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_rev_review_audit_logs_review_created ON rev_review_audit_logs (review_id, created_at);
CREATE INDEX idx_rev_review_audit_logs_operator_created ON rev_review_audit_logs (operator_id, created_at);

COMMENT ON TABLE rev_review_audit_logs IS '评价审核日志表';
COMMENT ON COLUMN rev_review_audit_logs.review_id IS '评价ID';
COMMENT ON COLUMN rev_review_audit_logs.action IS '操作：submit/approve/reject/delete/shield';
COMMENT ON COLUMN rev_review_audit_logs.operator_id IS '操作人ID';
COMMENT ON COLUMN rev_review_audit_logs.operator_name IS '操作人名称';
COMMENT ON COLUMN rev_review_audit_logs.before_status IS '变更前状态';
COMMENT ON COLUMN rev_review_audit_logs.after_status IS '变更后状态';
COMMENT ON COLUMN rev_review_audit_logs.remark IS '操作备注';
COMMENT ON COLUMN rev_review_audit_logs.snapshot IS '评价快照（用于回溯）';


CREATE TABLE rev_review_statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    target_type smallint NOT NULL,
    target_id bigint NOT NULL,
    rating_1_count int DEFAULT 0,
    rating_2_count int DEFAULT 0,
    rating_3_count int DEFAULT 0,
    rating_4_count int DEFAULT 0,
    rating_5_count int DEFAULT 0,
    total_count int DEFAULT 0,
    avg_rating rating_score DEFAULT 0.00,
    good_rate percentage DEFAULT 0.00,
    has_media_count int DEFAULT 0,
    has_content_count int DEFAULT 0,
    last_updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (target_type, target_id)
);

CREATE TRIGGER trg_rev_review_statistics_updated_at
    BEFORE UPDATE ON rev_review_statistics
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE rev_review_statistics IS '评价统计表（T+1或实时增量更新）';
COMMENT ON COLUMN rev_review_statistics.target_type IS '统计目标类型 1-SPU 2-商家';
COMMENT ON COLUMN rev_review_statistics.target_id IS '目标ID（SPU_ID或Merchant_ID）';
COMMENT ON COLUMN rev_review_statistics.rating_1_count IS '1星数量';
COMMENT ON COLUMN rev_review_statistics.rating_2_count IS '2星数量';
COMMENT ON COLUMN rev_review_statistics.rating_3_count IS '3星数量';
COMMENT ON COLUMN rev_review_statistics.rating_4_count IS '4星数量';
COMMENT ON COLUMN rev_review_statistics.rating_5_count IS '5星数量';
COMMENT ON COLUMN rev_review_statistics.total_count IS '总评价数';
COMMENT ON COLUMN rev_review_statistics.avg_rating IS '平均评分';
COMMENT ON COLUMN rev_review_statistics.good_rate IS '好评率（%）';
COMMENT ON COLUMN rev_review_statistics.has_media_count IS '带图评价数';
COMMENT ON COLUMN rev_review_statistics.has_content_count IS '有内容评价数';


CREATE TABLE rev_review_usefulness (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    review_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (review_id, user_id)
);

CREATE INDEX idx_rev_review_usefulness_review ON rev_review_usefulness (review_id);

COMMENT ON TABLE rev_review_usefulness IS '评价有用记录表（用于防刷和计数）';
COMMENT ON COLUMN rev_review_usefulness.review_id IS '评价ID';
COMMENT ON COLUMN rev_review_usefulness.user_id IS '用户ID';
