-- ============================================================
-- sp_p5.sql — PostgreSQL
-- 商品历史版本表（依赖 P1: products）
-- ============================================================

CREATE TABLE sp_product_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    version int NOT NULL,
    diff jsonb NOT NULL,
    changed_fields text[] DEFAULT NULL,
    operator varchar(50) DEFAULT '',
    operator_id bigint DEFAULT 0,
    reason varchar(500) DEFAULT '',
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_sp_product_versions_product ON sp_product_versions (product_id, version DESC);
CREATE INDEX idx_sp_product_versions_created_at ON sp_product_versions (created_at);

COMMENT ON TABLE sp_product_versions IS '商品SPU编辑历史版本表（每次编辑记录diff，保留最近10个版本）';
COMMENT ON COLUMN sp_product_versions.product_id IS '关联 sp_products.id';
COMMENT ON COLUMN sp_product_versions.version IS '版本号（从1递增）';
COMMENT ON COLUMN sp_product_versions.diff IS '变更JSON（{"before": {...}, "after": {...}}）';
COMMENT ON COLUMN sp_product_versions.changed_fields IS '变更字段名数组（如：{name, price, status}）';
COMMENT ON COLUMN sp_product_versions.operator IS '操作人';
COMMENT ON COLUMN sp_product_versions.operator_id IS '操作人ID';
COMMENT ON COLUMN sp_product_versions.reason IS '变更原因';
