-- ============================================================
-- sp_p1.sql — PostgreSQL
-- 商品域核心业务表（依赖 P0）
-- ============================================================

CREATE TABLE sp_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    category_id bigint NOT NULL,
    input_type input_type NOT NULL DEFAULT 'text',
    values text[] DEFAULT NULL,
    unit varchar(20) DEFAULT '',
    required smallint NOT NULL DEFAULT 0,
    searchable smallint NOT NULL DEFAULT 0,
    is_sku_spec smallint NOT NULL DEFAULT 0,
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_sp_attributes_category ON sp_attributes (category_id);
CREATE INDEX idx_sp_attributes_is_sku_spec ON sp_attributes (is_sku_spec);
CREATE INDEX idx_sp_attributes_searchable ON sp_attributes (category_id, searchable, status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_sp_attributes_updated_at
    BEFORE UPDATE ON sp_attributes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_attributes IS '属性字典表';
COMMENT ON COLUMN sp_attributes.name IS '属性名称（如：处理器、屏幕尺寸）';
COMMENT ON COLUMN sp_attributes.category_id IS '所属类目ID（该属性只出现在这个类目下）';
COMMENT ON COLUMN sp_attributes.input_type IS 'text-文本输入 radio-单选 checkbox-多选 number-数字';
COMMENT ON COLUMN sp_attributes.values IS '可选值列表（如["A15","A16"]，仅单选/多选时使用）';
COMMENT ON COLUMN sp_attributes.unit IS '单位（如：英寸、GB）';
COMMENT ON COLUMN sp_attributes.required IS '1-必填（该属性在该类目下创建商品时必须填写）';
COMMENT ON COLUMN sp_attributes.searchable IS '1-作为前台筛选条件（列表页筛选项来源）';
COMMENT ON COLUMN sp_attributes.is_sku_spec IS '1-是SKU规格（如颜色、内存） 0-仅SPU属性（如上市时间）';


CREATE TABLE sp_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL DEFAULT 0,
    name varchar(200) NOT NULL,
    subtitle varchar(500) DEFAULT '',
    category_id bigint NOT NULL DEFAULT 0,
    brand_id bigint NOT NULL DEFAULT 0,
    unit varchar(10) DEFAULT '件',
    main_image varchar(512) NOT NULL DEFAULT '',
    images text[] DEFAULT NULL,
    video_url varchar(512) DEFAULT '',
    min_price bigint NOT NULL DEFAULT 0,
    max_price bigint NOT NULL DEFAULT 0,
    total_stock int NOT NULL DEFAULT 0,
    sales_count int NOT NULL DEFAULT 0,
    rating_average numeric(3,2) NOT NULL DEFAULT 0.00,
    rating_count int NOT NULL DEFAULT 0,
    status product_status NOT NULL DEFAULT 'draft',
    sort_order int NOT NULL DEFAULT 0,
    has_description smallint NOT NULL DEFAULT 0,
    created_by bigint NOT NULL DEFAULT 0,
    updated_by bigint NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    -- 全文搜索向量（A=商品名称, B=副标题，由触发器自动维护）
    search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('simple', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(subtitle, '')), 'B')
    ) STORED,
    PRIMARY KEY (id)
);

CREATE INDEX idx_sp_products_search ON sp_products USING GIN (search_vector);
CREATE INDEX idx_sp_products_merchant ON sp_products (merchant_id)
    WHERE deleted_at IS NULL;
-- 覆盖索引：列表页避免回表（名称、价格、图片）
CREATE INDEX idx_sp_products_category_list ON sp_products (category_id, status, sort_order DESC, id DESC)
    INCLUDE (name, min_price, max_price, main_image, sales_count)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sp_products_brand_status ON sp_products (brand_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sp_products_status_sales ON sp_products (status, sales_count DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sp_products_status_rating ON sp_products (status, rating_average DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sp_products_created_at ON sp_products (created_at);

CREATE TRIGGER trg_sp_products_updated_at
    BEFORE UPDATE ON sp_products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_products IS '商品SPU主表（前台展示聚合层）';
COMMENT ON COLUMN sp_products.id IS 'SPU ID';
COMMENT ON COLUMN sp_products.merchant_id IS '所属商家ID';
COMMENT ON COLUMN sp_products.name IS '商品名称（用于搜索和展示）';
COMMENT ON COLUMN sp_products.subtitle IS '商品副标题（卖点文案，如"2026新款"）';
COMMENT ON COLUMN sp_products.category_id IS '前台主类目ID（叶子节点）';
COMMENT ON COLUMN sp_products.brand_id IS '品牌ID';
COMMENT ON COLUMN sp_products.unit IS '单位（件/箱/台/套）';
COMMENT ON COLUMN sp_products.main_image IS '主图URL（CDN地址）';
COMMENT ON COLUMN sp_products.images IS '附图JSON数组（最多10张）';
COMMENT ON COLUMN sp_products.video_url IS '主图视频URL';
COMMENT ON COLUMN sp_products.min_price IS 'SKU最低价（分）';
COMMENT ON COLUMN sp_products.max_price IS 'SKU最高价（分）';
COMMENT ON COLUMN sp_products.total_stock IS '可售库存总和（SUM(quantity - reserved)）';
COMMENT ON COLUMN sp_products.sales_count IS '总销量（从订单明细聚合，每日更新）';
COMMENT ON COLUMN sp_products.rating_average IS '平均评分（1-5）';
COMMENT ON COLUMN sp_products.rating_count IS '评价总数';
COMMENT ON COLUMN sp_products.status IS 'draft-草稿 pending_review-待审 listed-已上架 delisted-已下架 banned-违规封禁';
COMMENT ON COLUMN sp_products.sort_order IS '排序权重（越大越靠前，运营手动调整）';
COMMENT ON COLUMN sp_products.has_description IS '1-有图文详情（存于sp_product_descriptions表）';
COMMENT ON COLUMN sp_products.created_by IS '创建人ID';
COMMENT ON COLUMN sp_products.updated_by IS '最后更新人ID';
