-- ============================================================
-- sp_p2.sql — PostgreSQL
-- 商品域关联业务表（依赖 P1）
-- ============================================================

CREATE TABLE sp_category_brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (category_id, brand_id)
);

CREATE INDEX idx_sp_category_brands_brand_id ON sp_category_brands (brand_id);

COMMENT ON TABLE sp_category_brands IS '类目-品牌关联表（多对多）';
COMMENT ON COLUMN sp_category_brands.category_id IS '关联categories.id';
COMMENT ON COLUMN sp_category_brands.brand_id IS '关联brands.id';
COMMENT ON COLUMN sp_category_brands.sort_order IS '排序权重（越小越靠前，控制该类目下品牌的展示顺序）';


CREATE TABLE sp_category_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    attribute_id bigint NOT NULL,
    required smallint NOT NULL DEFAULT 0,
    is_default_filter smallint NOT NULL DEFAULT 0,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (category_id, attribute_id)
);

CREATE INDEX idx_sp_category_attributes_category ON sp_category_attributes (category_id);

COMMENT ON TABLE sp_category_attributes IS '类目-属性关联表（推荐模板）';
COMMENT ON COLUMN sp_category_attributes.category_id IS '类目ID';
COMMENT ON COLUMN sp_category_attributes.attribute_id IS '属性ID';
COMMENT ON COLUMN sp_category_attributes.required IS '该类目下是否必填（仅提示，非强校验）';
COMMENT ON COLUMN sp_category_attributes.is_default_filter IS '是否作为前台默认筛选项';
COMMENT ON COLUMN sp_category_attributes.sort_order IS '排序';


CREATE TABLE sp_skus (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    sku_code varchar(100) NOT NULL,
    barcode varchar(50) DEFAULT '',
    spec jsonb NOT NULL,
    spec_signature varchar(32) NOT NULL DEFAULT '',
    price bigint NOT NULL,
    market_price bigint NOT NULL DEFAULT 0,
    cost_price bigint NOT NULL DEFAULT 0,
    weight numeric(10,2) NOT NULL DEFAULT 0.00,
    volume numeric(10,2) NOT NULL DEFAULT 0.00,
    length numeric(10,2) NOT NULL DEFAULT 0.00,
    width numeric(10,2) NOT NULL DEFAULT 0.00,
    height numeric(10,2) NOT NULL DEFAULT 0.00,
    min_purchase_qty int NOT NULL DEFAULT 1,
    max_purchase_qty int NOT NULL DEFAULT 0,
    image varchar(512) DEFAULT '',
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (sku_code),
    UNIQUE (barcode)
);

CREATE INDEX idx_sp_skus_merchant ON sp_skus (merchant_id);
CREATE INDEX idx_sp_skus_product_id ON sp_skus (product_id);
CREATE INDEX idx_sp_skus_product_status ON sp_skus (product_id, status);
CREATE INDEX idx_sp_skus_deleted_at ON sp_skus (deleted_at);

CREATE TRIGGER trg_sp_skus_updated_at
    BEFORE UPDATE ON sp_skus
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_skus IS 'SKU规格表（具体可售单元）';
COMMENT ON COLUMN sp_skus.id IS 'SKU ID';
COMMENT ON COLUMN sp_skus.product_id IS '关联products.id';
COMMENT ON COLUMN sp_skus.merchant_id IS '所属商家ID';
COMMENT ON COLUMN sp_skus.sku_code IS '商家编码（唯一，用于ERP/WMS对接）';
COMMENT ON COLUMN sp_skus.barcode IS '条码/EAN/UPC（仓库扫描用）';
COMMENT ON COLUMN sp_skus.spec IS '规格JSON（如{"颜色":"红色","内存":"256G"}）';
COMMENT ON COLUMN sp_skus.spec_signature IS '规格MD5签名（用于快速匹配，由应用层计算）';
COMMENT ON COLUMN sp_skus.price IS '销售价（分）';
COMMENT ON COLUMN sp_skus.market_price IS '划线价/市场价（分）';
COMMENT ON COLUMN sp_skus.cost_price IS '成本价（分，仅后台可见）';
COMMENT ON COLUMN sp_skus.weight IS '重量（克）';
COMMENT ON COLUMN sp_skus.volume IS '体积（立方厘米）';
COMMENT ON COLUMN sp_skus.length IS '长（厘米）';
COMMENT ON COLUMN sp_skus.width IS '宽（厘米）';
COMMENT ON COLUMN sp_skus.height IS '高（厘米）';
COMMENT ON COLUMN sp_skus.min_purchase_qty IS '最少购买数量';
COMMENT ON COLUMN sp_skus.max_purchase_qty IS '最大购买数量（0=不限）';
COMMENT ON COLUMN sp_skus.image IS 'SKU专属图（如不同颜色展示不同图片）';
COMMENT ON COLUMN sp_skus.status IS '1-正常 0-禁用（如某规格暂时缺货下架）';


CREATE TABLE sp_product_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    attribute_id bigint NOT NULL,
    attribute_value_id bigint DEFAULT NULL,
    value varchar(500) NOT NULL,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (product_id, attribute_id, attribute_value_id)
);

CREATE INDEX idx_sp_product_attributes_attribute ON sp_product_attributes (attribute_id);
CREATE INDEX idx_sp_product_attributes_attribute_value ON sp_product_attributes (attribute_value_id);
CREATE INDEX idx_sp_product_attributes_deleted_at ON sp_product_attributes (deleted_at);

CREATE TRIGGER trg_sp_product_attributes_updated_at
    BEFORE UPDATE ON sp_product_attributes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_product_attributes IS 'SPU扩展属性值表';
COMMENT ON COLUMN sp_product_attributes.product_id IS '关联products.id';
COMMENT ON COLUMN sp_product_attributes.attribute_id IS '关联attributes.id';
COMMENT ON COLUMN sp_product_attributes.attribute_value_id IS '引用属性值字典ID（可选，关联attribute_values.id）';
COMMENT ON COLUMN sp_product_attributes.value IS '属性值（如：A16）';
COMMENT ON COLUMN sp_product_attributes.sort_order IS '排序权重（越小越靠前，用于控制前台展示顺序）';


CREATE TABLE sp_attribute_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    attribute_id bigint NOT NULL,
    value varchar(200) NOT NULL,
    alias jsonb DEFAULT NULL,
    search_weight int NOT NULL DEFAULT 0,
    numeric_value numeric(18,4) DEFAULT NULL,
    color_hex varchar(10) DEFAULT '',
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (attribute_id, value)
);

CREATE INDEX idx_sp_attr_values_attr_filter ON sp_attribute_values (attribute_id, status, numeric_value);
CREATE INDEX idx_sp_attr_values_search_weight ON sp_attribute_values (attribute_id, search_weight);

COMMENT ON TABLE sp_attribute_values IS '属性值字典表';
COMMENT ON COLUMN sp_attribute_values.attribute_id IS '关联属性ID';
COMMENT ON COLUMN sp_attribute_values.value IS '属性值（如：256G、红色）';
COMMENT ON COLUMN sp_attribute_values.alias IS '别名列表，用于搜索纠错、模糊匹配';
COMMENT ON COLUMN sp_attribute_values.search_weight IS '搜索权重（值越大匹配优先级越高）';
COMMENT ON COLUMN sp_attribute_values.numeric_value IS '数值型值（用于区间筛选）';
COMMENT ON COLUMN sp_attribute_values.color_hex IS '颜色色值（#FF0000）';
COMMENT ON COLUMN sp_attribute_values.sort_order IS '排序权重';
COMMENT ON COLUMN sp_attribute_values.status IS '1-启用 0-禁用';


CREATE TABLE sp_sku_specs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sku_id bigint NOT NULL,
    attribute_id bigint NOT NULL,
    attribute_value_id bigint NOT NULL,
    sort_order int NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (sku_id, attribute_id)
);

CREATE INDEX idx_sp_sku_specs_attr_value ON sp_sku_specs (attribute_id, attribute_value_id, sku_id);

COMMENT ON TABLE sp_sku_specs IS 'SKU规格值表（EAV模型）';
COMMENT ON COLUMN sp_sku_specs.sku_id IS '关联SKU ID';
COMMENT ON COLUMN sp_sku_specs.attribute_id IS '关联属性ID';
COMMENT ON COLUMN sp_sku_specs.attribute_value_id IS '关联属性值ID';
COMMENT ON COLUMN sp_sku_specs.sort_order IS '展示顺序';


CREATE TABLE sp_product_descriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    description text,
    mobile_description text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (product_id)
);

CREATE TRIGGER trg_sp_product_descriptions_updated_at
    BEFORE UPDATE ON sp_product_descriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_product_descriptions IS '商品详情表（从主表拆出，减少主表体积）';
COMMENT ON COLUMN sp_product_descriptions.product_id IS '关联products.id';
COMMENT ON COLUMN sp_product_descriptions.description IS '商品详情（富文本HTML）';
COMMENT ON COLUMN sp_product_descriptions.mobile_description IS '移动端详情（可选，适配手机展示）';
