-- ============================================================
-- sp_p3.sql — PostgreSQL
-- 库存相关表（依赖 P2: skus）
-- ============================================================

CREATE TABLE sp_inventories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sku_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    warehouse_id bigint NOT NULL DEFAULT 0,
    quantity bigint NOT NULL DEFAULT 0,
    reserved bigint NOT NULL DEFAULT 0,
    available bigint GENERATED ALWAYS AS (quantity - reserved) STORED,
    in_transit bigint NOT NULL DEFAULT 0,
    threshold bigint NOT NULL DEFAULT 10,
    max_threshold bigint NOT NULL DEFAULT 999999,
    status inventory_status NOT NULL DEFAULT 'instock',
    -- 乐观锁版本号（并发扣库存校验）
    version int NOT NULL DEFAULT 0,
    last_counted_at timestamp DEFAULT NULL,
    last_counted_by varchar(50) DEFAULT '',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (sku_id, warehouse_id)
);

CREATE INDEX idx_sp_inventories_active ON sp_inventories (sku_id, warehouse_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sp_inventories_merchant ON sp_inventories (merchant_id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sp_inventories_available ON sp_inventories (available)
    WHERE deleted_at IS NULL;
-- 并发扣库存专用索引
CREATE INDEX idx_sp_inventories_sku_for_update ON sp_inventories (sku_id, warehouse_id, status);

CREATE TRIGGER trg_sp_inventories_updated_at
    BEFORE UPDATE ON sp_inventories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_inventories IS '库存表（支持多仓库）';
COMMENT ON COLUMN sp_inventories.id IS '库存记录ID';
COMMENT ON COLUMN sp_inventories.sku_id IS '关联skus.id';
COMMENT ON COLUMN sp_inventories.merchant_id IS '所属商家ID';
COMMENT ON COLUMN sp_inventories.warehouse_id IS '仓库ID（0表示主仓，未来扩展多仓，关联warehouse.id）';
COMMENT ON COLUMN sp_inventories.quantity IS '物理库存总量（含预占）';
COMMENT ON COLUMN sp_inventories.reserved IS '预占库存（下单未支付）';
COMMENT ON COLUMN sp_inventories.available IS '可售库存（quantity - reserved）';
COMMENT ON COLUMN sp_inventories.in_transit IS '在途库存（采购中/调拨中）';
COMMENT ON COLUMN sp_inventories.threshold IS '安全库存预警阈值（低于此值触发告警）';
COMMENT ON COLUMN sp_inventories.max_threshold IS '最大库存上限（入库不能超过此值）';
COMMENT ON COLUMN sp_inventories.status IS '库存状态：instock-充足 lowstock-缺货 outofstock-无货';
COMMENT ON COLUMN sp_inventories.last_counted_at IS '最后盘点时间';
COMMENT ON COLUMN sp_inventories.last_counted_by IS '最后盘点人';


CREATE TABLE sp_inventory_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sku_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    warehouse_id bigint NOT NULL DEFAULT 0,
    change_type varchar(30) NOT NULL,
    before_quantity bigint NOT NULL DEFAULT 0,
    after_quantity bigint NOT NULL DEFAULT 0,
    before_reserved bigint NOT NULL DEFAULT 0,
    after_reserved bigint NOT NULL DEFAULT 0,
    change_amount bigint NOT NULL DEFAULT 0,
    reference_id varchar(64) DEFAULT '',
    operator varchar(50) DEFAULT '',
    note varchar(500) DEFAULT '',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE INDEX idx_sp_inventory_logs_merchant ON sp_inventory_logs (merchant_id);
CREATE INDEX idx_sp_inventory_logs_sku_id ON sp_inventory_logs (sku_id, warehouse_id);
CREATE INDEX idx_sp_inventory_logs_change_type ON sp_inventory_logs (change_type);
CREATE INDEX idx_sp_inventory_logs_reference_id ON sp_inventory_logs (reference_id);
-- BRIN 索引：日志流水行为时间序
CREATE INDEX idx_sp_inventory_logs_time_brin ON sp_inventory_logs USING BRIN (created_at)
    WITH (pages_per_range = 32);

COMMENT ON TABLE sp_inventory_logs IS '库存变更流水表（对账与审计）';
COMMENT ON COLUMN sp_inventory_logs.id IS '日志ID';
COMMENT ON COLUMN sp_inventory_logs.sku_id IS '关联skus.id';
COMMENT ON COLUMN sp_inventory_logs.merchant_id IS '所属商家ID';
COMMENT ON COLUMN sp_inventory_logs.warehouse_id IS '仓库ID';
COMMENT ON COLUMN sp_inventory_logs.change_type IS '变更类型：order_lock-下单预占 order_unlock-取消释放 order_dedut-支付扣减 inbound-入库 outbound-出库 return-退货入库 adjust-盘盈亏修正';
COMMENT ON COLUMN sp_inventory_logs.before_quantity IS '变更前物理库存';
COMMENT ON COLUMN sp_inventory_logs.after_quantity IS '变更后物理库存';
COMMENT ON COLUMN sp_inventory_logs.before_reserved IS '变更前预占库存';
COMMENT ON COLUMN sp_inventory_logs.after_reserved IS '变更后预占库存';
COMMENT ON COLUMN sp_inventory_logs.change_amount IS '变更数量（正=增加，负=减少）';
COMMENT ON COLUMN sp_inventory_logs.reference_id IS '关联单据ID（如订单号、入库单号）';
COMMENT ON COLUMN sp_inventory_logs.operator IS '操作人（系统操作填system）';
COMMENT ON COLUMN sp_inventory_logs.note IS '备注';
