-- ============================================================
-- sp_p4.sql — PostgreSQL
-- 仓库相关表（MCH多商户扩展，依赖 P2: skus）
-- ============================================================

CREATE TABLE sp_warehouses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL DEFAULT 0,
    warehouse_name varchar(100) NOT NULL,
    warehouse_type smallint NOT NULL DEFAULT 1,
    status smallint NOT NULL DEFAULT 1,
    province varchar(32) DEFAULT '',
    city varchar(32) DEFAULT '',
    district varchar(32) DEFAULT '',
    address varchar(255) DEFAULT '',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_sp_warehouses_merchant ON sp_warehouses (merchant_id);
CREATE INDEX idx_sp_warehouses_status ON sp_warehouses (status);
CREATE INDEX idx_sp_warehouses_deleted_at ON sp_warehouses (deleted_at);

CREATE TRIGGER trg_sp_warehouses_updated_at
    BEFORE UPDATE ON sp_warehouses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_warehouses IS '仓库表';
COMMENT ON COLUMN sp_warehouses.id IS '仓库ID';
COMMENT ON COLUMN sp_warehouses.merchant_id IS '所属商家ID（0表示平台仓）';
COMMENT ON COLUMN sp_warehouses.warehouse_name IS '仓库名称';
COMMENT ON COLUMN sp_warehouses.warehouse_type IS '1-平台仓 2-商家仓 3-第三方仓';
COMMENT ON COLUMN sp_warehouses.status IS '1-启用 2-禁用';
COMMENT ON COLUMN sp_warehouses.province IS '省';
COMMENT ON COLUMN sp_warehouses.city IS '市';
COMMENT ON COLUMN sp_warehouses.district IS '区';
COMMENT ON COLUMN sp_warehouses.address IS '详细地址';


CREATE TABLE sp_warehouse_skus (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    warehouse_id bigint NOT NULL,
    sku_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    stock_qty bigint NOT NULL DEFAULT 0,
    reserved_qty bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (warehouse_id, sku_id)
);

CREATE INDEX idx_sp_warehouse_skus_merchant ON sp_warehouse_skus (merchant_id);
CREATE INDEX idx_sp_warehouse_skus_deleted_at ON sp_warehouse_skus (deleted_at);

CREATE TRIGGER trg_sp_warehouse_skus_updated_at
    BEFORE UPDATE ON sp_warehouse_skus
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_warehouse_skus IS '仓库SKU映射表';
COMMENT ON COLUMN sp_warehouse_skus.id IS '主键';
COMMENT ON COLUMN sp_warehouse_skus.warehouse_id IS '仓库ID';
COMMENT ON COLUMN sp_warehouse_skus.sku_id IS 'SKU ID';
COMMENT ON COLUMN sp_warehouse_skus.merchant_id IS '所属商家ID';
COMMENT ON COLUMN sp_warehouse_skus.stock_qty IS '库存数量';
COMMENT ON COLUMN sp_warehouse_skus.reserved_qty IS '预占数量';
COMMENT ON COLUMN sp_warehouse_skus.status IS '1-可用 2-停用';
