-- ============================================================
-- sp_p0.sql — PostgreSQL
-- 商品域独立基础表
-- ============================================================

CREATE TABLE sp_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    parent_id bigint NOT NULL DEFAULT 0,
    level smallint NOT NULL DEFAULT 1,
    path varchar(500) NOT NULL DEFAULT '',
    icon_url varchar(512) DEFAULT '',
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_sp_categories_parent_id ON sp_categories (parent_id);
CREATE INDEX idx_sp_categories_path ON sp_categories (path);
CREATE INDEX idx_sp_categories_level_status ON sp_categories (level, status);

CREATE TRIGGER trg_sp_categories_updated_at
    BEFORE UPDATE ON sp_categories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_categories IS '类目表（树状结构）';
COMMENT ON COLUMN sp_categories.name IS '类目名称（如：手机）';
COMMENT ON COLUMN sp_categories.parent_id IS '父级ID（0表示根节点）';
COMMENT ON COLUMN sp_categories.level IS '层级（1-3级）';
COMMENT ON COLUMN sp_categories.path IS '路径（如：1/23/45/）';
COMMENT ON COLUMN sp_categories.icon_url IS '类目图标';
COMMENT ON COLUMN sp_categories.sort_order IS '排序';
COMMENT ON COLUMN sp_categories.status IS '1-启用 0-禁用';


CREATE TABLE sp_brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    english_name varchar(100) DEFAULT '',
    logo_url varchar(512) DEFAULT '',
    first_letter char(1) DEFAULT '',
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    description text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE INDEX idx_sp_brands_first_letter ON sp_brands (first_letter);
CREATE INDEX idx_sp_brands_status ON sp_brands (status);
-- Trigram 索引：品牌名模糊搜索与纠错（需 pg_trgm 扩展）
CREATE INDEX idx_sp_brands_name_trgm ON sp_brands USING GIN (name gin_trgm_ops);

CREATE TRIGGER trg_sp_brands_updated_at
    BEFORE UPDATE ON sp_brands
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_brands IS '品牌表';
COMMENT ON COLUMN sp_brands.name IS '品牌名称（如：苹果）';
COMMENT ON COLUMN sp_brands.english_name IS '英文名';
COMMENT ON COLUMN sp_brands.logo_url IS '品牌Logo（CDN）';
COMMENT ON COLUMN sp_brands.first_letter IS '首字母（A-Z，用于前台索引筛选）';
COMMENT ON COLUMN sp_brands.sort_order IS '排序权重';
COMMENT ON COLUMN sp_brands.status IS '1-启用 0-禁用';
COMMENT ON COLUMN sp_brands.description IS '品牌故事';
