-- ============================================================
-- sp_p2.sql — PostgreSQL
-- 商品域关联业务表（依赖 P1）
-- ============================================================

CREATE TABLE sp_category_brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (category_id, brand_id)
);

CREATE INDEX idx_sp_category_brands_brand_id ON sp_category_brands (brand_id);

COMMENT ON TABLE sp_category_brands IS '类目-品牌关联表（多对多）';
COMMENT ON COLUMN sp_category_brands.category_id IS '关联categories.id';
COMMENT ON COLUMN sp_category_brands.brand_id IS '关联brands.id';
COMMENT ON COLUMN sp_category_brands.sort_order IS '排序权重（越小越靠前，控制该类目下品牌的展示顺序）';


CREATE TABLE sp_skus (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    sku_code varchar(100) NOT NULL,
    barcode varchar(50) DEFAULT '',
    spec jsonb NOT NULL,
    spec_signature varchar(32) NOT NULL DEFAULT '',
    price bigint NOT NULL,
    market_price bigint NOT NULL DEFAULT 0,
    cost_price bigint NOT NULL DEFAULT 0,
    weight numeric(10,2) NOT NULL DEFAULT 0.00,
    volume numeric(10,2) NOT NULL DEFAULT 0.00,
    length numeric(10,2) NOT NULL DEFAULT 0.00,
    width numeric(10,2) NOT NULL DEFAULT 0.00,
    height numeric(10,2) NOT NULL DEFAULT 0.00,
    min_purchase_qty int NOT NULL DEFAULT 1,
    max_purchase_qty int NOT NULL DEFAULT 0,
    image varchar(512) DEFAULT '',
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (sku_code),
    UNIQUE (barcode)
);

CREATE INDEX idx_sp_skus_merchant ON sp_skus (merchant_id);
CREATE INDEX idx_sp_skus_product_id ON sp_skus (product_id);
CREATE INDEX idx_sp_skus_product_status ON sp_skus (product_id, status);
CREATE INDEX idx_sp_skus_deleted_at ON sp_skus (deleted_at);

CREATE TRIGGER trg_sp_skus_updated_at
    BEFORE UPDATE ON sp_skus
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_skus IS 'SKU规格表（具体可售单元）';
COMMENT ON COLUMN sp_skus.id IS 'SKU ID';
COMMENT ON COLUMN sp_skus.product_id IS '关联products.id';
COMMENT ON COLUMN sp_skus.merchant_id IS '所属商家ID';
COMMENT ON COLUMN sp_skus.sku_code IS '商家编码（唯一，用于ERP/WMS对接）';
COMMENT ON COLUMN sp_skus.barcode IS '条码/EAN/UPC（仓库扫描用）';
COMMENT ON COLUMN sp_skus.spec IS '规格JSON（如{"颜色":"红色","内存":"256G"}）';
COMMENT ON COLUMN sp_skus.spec_signature IS '规格MD5签名（用于快速匹配，由应用层计算）';
COMMENT ON COLUMN sp_skus.price IS '销售价（分）';
COMMENT ON COLUMN sp_skus.market_price IS '划线价/市场价（分）';
COMMENT ON COLUMN sp_skus.cost_price IS '成本价（分，仅后台可见）';
COMMENT ON COLUMN sp_skus.weight IS '重量（克）';
COMMENT ON COLUMN sp_skus.volume IS '体积（立方厘米）';
COMMENT ON COLUMN sp_skus.length IS '长（厘米）';
COMMENT ON COLUMN sp_skus.width IS '宽（厘米）';
COMMENT ON COLUMN sp_skus.height IS '高（厘米）';
COMMENT ON COLUMN sp_skus.min_purchase_qty IS '最少购买数量';
COMMENT ON COLUMN sp_skus.max_purchase_qty IS '最大购买数量（0=不限）';
COMMENT ON COLUMN sp_skus.image IS 'SKU专属图（如不同颜色展示不同图片）';
COMMENT ON COLUMN sp_skus.status IS '1-正常 0-禁用（如某规格暂时缺货下架）';


CREATE TABLE sp_product_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    attribute_id bigint NOT NULL,
    value varchar(500) NOT NULL,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (product_id, attribute_id)
);

CREATE INDEX idx_sp_product_attributes_attribute ON sp_product_attributes (attribute_id);
CREATE INDEX idx_sp_product_attributes_deleted_at ON sp_product_attributes (deleted_at);

CREATE TRIGGER trg_sp_product_attributes_updated_at
    BEFORE UPDATE ON sp_product_attributes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_product_attributes IS 'SPU扩展属性值表';
COMMENT ON COLUMN sp_product_attributes.product_id IS '关联products.id';
COMMENT ON COLUMN sp_product_attributes.attribute_id IS '关联attributes.id';
COMMENT ON COLUMN sp_product_attributes.value IS '属性值（如：A16）';
COMMENT ON COLUMN sp_product_attributes.sort_order IS '排序权重（越小越靠前，用于控制前台展示顺序）';


CREATE TABLE sp_product_descriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    description text,
    mobile_description text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (product_id)
);

CREATE TRIGGER trg_sp_product_descriptions_updated_at
    BEFORE UPDATE ON sp_product_descriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sp_product_descriptions IS '商品详情表（从主表拆出，减少主表体积）';
COMMENT ON COLUMN sp_product_descriptions.product_id IS '关联products.id';
COMMENT ON COLUMN sp_product_descriptions.description IS '商品详情（富文本HTML）';
COMMENT ON COLUMN sp_product_descriptions.mobile_description IS '移动端详情（可选，适配手机展示）';
