-- ============================================================
-- sys_p0.sql — PostgreSQL
-- 系统员工域（B端后台）
-- RBAC + 员工管理，与 C端消费者域（usr_*）完全隔离
-- ============================================================

-- ==================== 角色定义 ====================

CREATE TABLE sys_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    display_name varchar(100) NOT NULL DEFAULT '',
    description varchar(255) NOT NULL DEFAULT '',
    role_type varchar(20) NOT NULL DEFAULT 'custom',
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE INDEX idx_sys_roles_type ON sys_roles (role_type);
CREATE INDEX idx_sys_roles_status ON sys_roles (status);
CREATE INDEX idx_sys_roles_deleted_at ON sys_roles (deleted_at);

CREATE TRIGGER trg_sys_roles_updated_at
    BEFORE UPDATE ON sys_roles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sys_roles IS 'B端角色定义表';


CREATE TABLE sys_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    display_name varchar(100) NOT NULL DEFAULT '',
    description varchar(255) NOT NULL DEFAULT '',
    resource varchar(50) NOT NULL,
    action varchar(50) NOT NULL,
    category varchar(50) NOT NULL DEFAULT '',
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE INDEX idx_sys_permissions_resource ON sys_permissions (resource);
CREATE INDEX idx_sys_permissions_action ON sys_permissions (action);
CREATE INDEX idx_sys_permissions_status ON sys_permissions (status);
CREATE INDEX idx_sys_permissions_deleted_at ON sys_permissions (deleted_at);

CREATE TRIGGER trg_sys_permissions_updated_at
    BEFORE UPDATE ON sys_permissions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sys_permissions IS 'B端权限表';


CREATE TABLE sys_role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    scope_type varchar(20) NOT NULL DEFAULT 'platform',
    scope_id bigint NOT NULL DEFAULT 0,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (role_id, permission_id)
);

CREATE INDEX idx_sys_role_permissions_permission_id ON sys_role_permissions (permission_id);
CREATE INDEX idx_sys_role_permissions_scope ON sys_role_permissions (scope_type, scope_id);
CREATE INDEX idx_sys_role_permissions_deleted_at ON sys_role_permissions (deleted_at);

COMMENT ON TABLE sys_role_permissions IS '角色-权限关联表';


-- ==================== 员工管理 ====================

CREATE TABLE sys_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) NOT NULL,
    password_hash varchar(255) NOT NULL DEFAULT '',
    real_name varchar(50) NOT NULL DEFAULT '',
    email varchar(100) DEFAULT NULL,
    phone varchar(20) DEFAULT NULL,
    avatar varchar(512) DEFAULT '',
    status smallint NOT NULL DEFAULT 1,
    last_login_ip varchar(50) DEFAULT '',
    last_login_at timestamp(3) DEFAULT NULL,
    created_by bigint DEFAULT 0,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (username)
);

CREATE INDEX idx_sys_staff_status ON sys_staff (status);
CREATE INDEX idx_sys_staff_deleted_at ON sys_staff (deleted_at);

CREATE TRIGGER trg_sys_staff_updated_at
    BEFORE UPDATE ON sys_staff
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE sys_staff IS 'B端员工表（后台管理员/运营/财务等）';
COMMENT ON COLUMN sys_staff.username IS '登录用户名（唯一）';
COMMENT ON COLUMN sys_staff.password_hash IS 'bcrypt 密码哈希';
COMMENT ON COLUMN sys_staff.real_name IS '真实姓名';
COMMENT ON COLUMN sys_staff.status IS '1-正常 0-禁用';
COMMENT ON COLUMN sys_staff.created_by IS '创建人ID（0=系统）';


CREATE TABLE sys_staff_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    staff_id bigint NOT NULL,
    role_id bigint NOT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (staff_id, role_id)
);

CREATE INDEX idx_sys_staff_roles_role_id ON sys_staff_roles (role_id);
CREATE INDEX idx_sys_staff_roles_deleted_at ON sys_staff_roles (deleted_at);

COMMENT ON TABLE sys_staff_roles IS '员工-角色关联表（平台级角色）';


CREATE TABLE sys_login_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    staff_id bigint NOT NULL,
    login_ip varchar(50) NOT NULL DEFAULT '',
    login_device varchar(100) NOT NULL DEFAULT '',
    login_location varchar(100) NOT NULL DEFAULT '',
    login_method varchar(20) NOT NULL DEFAULT '',
    login_status smallint NOT NULL DEFAULT 1,
    failure_reason varchar(100) NOT NULL DEFAULT '',
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_sys_login_histories_staff_id ON sys_login_histories (staff_id);
CREATE INDEX idx_sys_login_histories_created_at ON sys_login_histories (created_at);

COMMENT ON TABLE sys_login_histories IS 'B端员工登录历史表';
