-- ============================================================
-- tx_p1.sql — PostgreSQL
-- 交易明细与日志表（依赖 P0: orders）
-- ============================================================

CREATE TABLE tx_cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id bigint NOT NULL,
    sku_id bigint NOT NULL,
    product_id bigint NOT NULL DEFAULT 0,
    product_name varchar(200) NOT NULL DEFAULT '',
    sku_spec jsonb DEFAULT NULL,
    image varchar(512) DEFAULT '',
    price bigint NOT NULL,
    quantity int NOT NULL DEFAULT 1,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (cart_id, sku_id)
);

CREATE INDEX idx_tx_cart_items_cart_id ON tx_cart_items (cart_id);
CREATE INDEX idx_tx_cart_items_sku_id ON tx_cart_items (sku_id);

CREATE TRIGGER trg_tx_cart_items_updated_at
    BEFORE UPDATE ON tx_cart_items
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_cart_items IS '购物车商品项';
COMMENT ON COLUMN tx_cart_items.cart_id IS '关联 tx_carts.id';
COMMENT ON COLUMN tx_cart_items.sku_id IS '关联 skus.id(sp_skus)';
COMMENT ON COLUMN tx_cart_items.product_id IS '关联 products.id(sp_products)，冗余用于展示';
COMMENT ON COLUMN tx_cart_items.product_name IS '商品名（冗余快照）';
COMMENT ON COLUMN tx_cart_items.sku_spec IS '规格JSON快照（如{"颜色":"红色","内存":"256G"}）';
COMMENT ON COLUMN tx_cart_items.image IS '商品图（冗余快照）';
COMMENT ON COLUMN tx_cart_items.price IS '加入时的价格（分，防止下单时价格变动导致纠纷）';
COMMENT ON COLUMN tx_cart_items.quantity IS '数量';


CREATE TABLE tx_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    sub_order_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    order_no varchar(32) NOT NULL,
    sub_order_no varchar(32) NOT NULL DEFAULT '',
    sku_id bigint NOT NULL,
    product_id bigint NOT NULL DEFAULT 0,
    sku_code varchar(100) DEFAULT '',
    product_name varchar(200) NOT NULL DEFAULT '',
    sku_spec_summary varchar(500) DEFAULT '',
    sku_spec jsonb DEFAULT NULL,
    image varchar(512) DEFAULT '',
    price bigint NOT NULL,
    quantity int NOT NULL DEFAULT 1,
    subtotal bigint NOT NULL DEFAULT 0,
    refund_status varchar(20) NOT NULL DEFAULT 'none',
    refund_amount bigint NOT NULL DEFAULT 0,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT chk_subtotal CHECK (subtotal >= 0)
);

CREATE INDEX idx_tx_order_items_order_no ON tx_order_items (order_no);
CREATE INDEX idx_tx_order_items_sku_id ON tx_order_items (sku_id);
CREATE INDEX idx_tx_order_items_sub_order_id ON tx_order_items (sub_order_id);

CREATE TRIGGER trg_tx_order_items_updated_at
    BEFORE UPDATE ON tx_order_items
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_order_items IS '订单明细表';
COMMENT ON COLUMN tx_order_items.order_id IS '关联 tx_orders.id';
COMMENT ON COLUMN tx_order_items.sub_order_id IS '子订单ID';
COMMENT ON COLUMN tx_order_items.merchant_id IS '所属商家ID';
COMMENT ON COLUMN tx_order_items.order_no IS '订单号（冗余，方便按订单号查）';
COMMENT ON COLUMN tx_order_items.sub_order_no IS '子订单号（冗余，方便按商家订单查）';
COMMENT ON COLUMN tx_order_items.sku_id IS '关联 skus.id(sp_skus)';
COMMENT ON COLUMN tx_order_items.product_id IS '关联 products.id(sp_products)';
COMMENT ON COLUMN tx_order_items.sku_code IS '商家编码（冗余快照）';
COMMENT ON COLUMN tx_order_items.product_name IS '商品名（冗余快照）';
COMMENT ON COLUMN tx_order_items.sku_spec_summary IS '规格摘要（如：红色 / 256G）';
COMMENT ON COLUMN tx_order_items.sku_spec IS '规格JSON快照';
COMMENT ON COLUMN tx_order_items.image IS '商品图（冗余快照）';
COMMENT ON COLUMN tx_order_items.price IS '单价（分，下单时价格）';
COMMENT ON COLUMN tx_order_items.quantity IS '购买数量';
COMMENT ON COLUMN tx_order_items.subtotal IS '小计（分 = price * quantity）';
COMMENT ON COLUMN tx_order_items.refund_status IS '退款状态：none-无 refunding-退款中 refunded-已退款';
COMMENT ON COLUMN tx_order_items.refund_amount IS '已退款金额（分）';


CREATE TABLE tx_order_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    order_no varchar(32) NOT NULL,
    from_status varchar(20) DEFAULT '',
    to_status varchar(20) NOT NULL,
    operator varchar(50) DEFAULT 'system',
    operator_type varchar(20) DEFAULT 'system',
    note varchar(500) DEFAULT '',
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_tx_order_logs_order_id ON tx_order_logs (order_id);
-- BRIN 索引：日志流水行为时间序
CREATE INDEX idx_tx_order_logs_time_brin ON tx_order_logs USING BRIN (created_at)
    WITH (pages_per_range = 32);

COMMENT ON TABLE tx_order_logs IS '订单操作日志表（审计与对账）';
COMMENT ON COLUMN tx_order_logs.order_id IS '关联 tx_orders.id';
COMMENT ON COLUMN tx_order_logs.order_no IS '订单号（冗余，便于按号查日志）';
COMMENT ON COLUMN tx_order_logs.from_status IS '变更前状态';
COMMENT ON COLUMN tx_order_logs.to_status IS '变更后状态';
COMMENT ON COLUMN tx_order_logs.operator IS '操作人';
COMMENT ON COLUMN tx_order_logs.operator_type IS '操作人类型：system-系统 user-用户 admin-管理员';
COMMENT ON COLUMN tx_order_logs.note IS '备注（如：支付成功、超时取消）';
