-- ============================================================
-- tx_p0.sql — PostgreSQL
-- 交易域核心表
-- ============================================================

CREATE TABLE tx_carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    session_id varchar(64) DEFAULT '',
    expired_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_tx_carts_user_id ON tx_carts (user_id);
CREATE INDEX idx_tx_carts_session_id ON tx_carts (session_id);
CREATE INDEX idx_tx_carts_expired_at ON tx_carts (expired_at);

CREATE TRIGGER trg_tx_carts_updated_at
    BEFORE UPDATE ON tx_carts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_carts IS '购物车主表（session型购物车30天过期，用户型购物车90天未更新自动清理，每日定时任务扫描 expired_at）';
COMMENT ON COLUMN tx_carts.user_id IS '用户ID（已登录用户）';
COMMENT ON COLUMN tx_carts.session_id IS '会话ID（未登录时的临时标识）';
COMMENT ON COLUMN tx_carts.expired_at IS '过期时间（session 型购物车自动清理）';


CREATE TABLE tx_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_no varchar(32) NOT NULL,
    user_id bigint NOT NULL,
    total_amount bigint NOT NULL DEFAULT 0,
    discount_amount bigint NOT NULL DEFAULT 0,
    shipping_fee bigint NOT NULL DEFAULT 0,
    pay_amount bigint NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'pending',
    payment_status varchar(20) NOT NULL DEFAULT 'unpaid',
    payment_method varchar(32) DEFAULT '',
    consignee varchar(64) NOT NULL DEFAULT '',
    phone varchar(20) NOT NULL DEFAULT '',
    province varchar(32) DEFAULT '',
    city varchar(32) DEFAULT '',
    district varchar(32) DEFAULT '',
    detail_addr varchar(256) DEFAULT '',
    zip_code varchar(10) DEFAULT '',
    coupon_id bigint DEFAULT NULL,
    coupon_snapshot jsonb DEFAULT NULL,
    buyer_remark varchar(500) DEFAULT '',
    seller_remark varchar(500) DEFAULT '',
    source varchar(20) NOT NULL DEFAULT 'pc',
    paid_at timestamp(3) DEFAULT NULL,
    shipped_at timestamp(3) DEFAULT NULL,
    delivered_at timestamp(3) DEFAULT NULL,
    completed_at timestamp(3) DEFAULT NULL,
    closed_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (order_no),
    CONSTRAINT chk_pay_amount CHECK (pay_amount >= 0),
    CONSTRAINT chk_total_amount CHECK (total_amount >= 0)
);

CREATE INDEX idx_tx_orders_user_id_status ON tx_orders (user_id, status);
CREATE INDEX idx_tx_orders_status ON tx_orders (status);
CREATE INDEX idx_tx_orders_payment_status ON tx_orders (payment_status);
CREATE INDEX idx_tx_orders_created_at ON tx_orders (created_at);

CREATE TRIGGER trg_tx_orders_updated_at
    BEFORE UPDATE ON tx_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_orders IS '订单主表';
COMMENT ON COLUMN tx_orders.order_no IS '父订单号（业务唯一键，如 202612010001）';
COMMENT ON COLUMN tx_orders.user_id IS '用户ID';
COMMENT ON COLUMN tx_orders.total_amount IS '商品总金额（分）';
COMMENT ON COLUMN tx_orders.discount_amount IS '优惠金额（分，含优惠券/满减）';
COMMENT ON COLUMN tx_orders.shipping_fee IS '运费（分）';
COMMENT ON COLUMN tx_orders.pay_amount IS '实付金额（分 = total - discount + shipping）';
COMMENT ON COLUMN tx_orders.status IS '父订单状态：pending-待支付 paid-已支付 partial_shipped-部分发货 completed-已完成 cancelled-已取消 closed-已关闭 refunding-退款中 refunded-已退款';
COMMENT ON COLUMN tx_orders.payment_status IS '支付状态：unpaid-未支付 paying-支付中 paid-已支付 refunding-退款中 refunded-已退款';
COMMENT ON COLUMN tx_orders.payment_method IS '支付方式：wechat-微信 alipay-支付宝 wallet-余额';
COMMENT ON COLUMN tx_orders.consignee IS '收货人';
COMMENT ON COLUMN tx_orders.phone IS '联系电话';
COMMENT ON COLUMN tx_orders.source IS '订单来源：pc-电脑端 app-APP miniapp-小程序 h5-H5';
COMMENT ON COLUMN tx_orders.coupon_id IS '使用的优惠券ID';
COMMENT ON COLUMN tx_orders.coupon_snapshot IS '优惠券快照（名称/面值等，便于售后追溯）';
COMMENT ON COLUMN tx_orders.buyer_remark IS '买家备注';
COMMENT ON COLUMN tx_orders.seller_remark IS '卖家备注';


CREATE TABLE tx_sub_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sub_order_no varchar(32) NOT NULL,
    parent_order_id bigint NOT NULL,
    parent_order_no varchar(32) NOT NULL,
    user_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    total_amount bigint NOT NULL DEFAULT 0,
    discount_amount bigint NOT NULL DEFAULT 0,
    shipping_fee bigint NOT NULL DEFAULT 0,
    pay_amount bigint NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'pending',
    refund_status varchar(20) NOT NULL DEFAULT 'none',
    seller_remark varchar(500) DEFAULT '',
    paid_at timestamp(3) DEFAULT NULL,
    shipped_at timestamp(3) DEFAULT NULL,
    delivered_at timestamp(3) DEFAULT NULL,
    completed_at timestamp(3) DEFAULT NULL,
    closed_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (sub_order_no),
    CONSTRAINT chk_sub_pay_amount CHECK (pay_amount >= 0)
);

CREATE INDEX idx_tx_sub_orders_parent_order_no ON tx_sub_orders (parent_order_no);
CREATE INDEX idx_tx_sub_orders_merchant_status ON tx_sub_orders (merchant_id, status);
CREATE INDEX idx_tx_sub_orders_user_status ON tx_sub_orders (user_id, status);
CREATE INDEX idx_tx_sub_orders_created_at ON tx_sub_orders (created_at);

CREATE TRIGGER trg_tx_sub_orders_updated_at
    BEFORE UPDATE ON tx_sub_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_sub_orders IS '子订单表（父订单按商家拆分）';
COMMENT ON COLUMN tx_sub_orders.sub_order_no IS '子订单号（按商家拆单后的业务唯一键）';
COMMENT ON COLUMN tx_sub_orders.parent_order_id IS '父订单ID';
COMMENT ON COLUMN tx_sub_orders.parent_order_no IS '父订单号（冗余，便于查询）';
COMMENT ON COLUMN tx_sub_orders.user_id IS '用户ID';
COMMENT ON COLUMN tx_sub_orders.merchant_id IS '所属商家ID';
COMMENT ON COLUMN tx_sub_orders.status IS '子订单状态：pending-待支付 paid-已支付 shipped-已发货 delivered-已签收 completed-已完成 cancelled-已取消 closed-已关闭 refunding-退款中 refunded-已退款';
COMMENT ON COLUMN tx_sub_orders.refund_status IS '退款状态：none-无 partial_refunded-部分退款 refunded-已退款';
COMMENT ON COLUMN tx_sub_orders.seller_remark IS '卖家备注';
