-- ============================================================
-- tx_p3.sql — PostgreSQL
-- 售后相关表（MCH 多商户扩展，依赖 P0: orders）
-- ============================================================

CREATE TABLE tx_after_sales (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    after_sale_no varchar(32) NOT NULL,
    order_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    merchant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    after_sale_type after_sale_type NOT NULL,
    apply_quantity int NOT NULL DEFAULT 1,
    reason varchar(500) DEFAULT '',
    amount bigint NOT NULL DEFAULT 0,
    refund_id bigint DEFAULT NULL,
    refund_no varchar(32) DEFAULT '',
    status smallint NOT NULL DEFAULT 0,
    return_carrier varchar(20) DEFAULT '',
    return_tracking_no varchar(64) DEFAULT '',
    return_shipped_at timestamp(3) DEFAULT NULL,
    merchant_received_at timestamp(3) DEFAULT NULL,
    apply_at timestamp(3) DEFAULT NULL,
    audited_at timestamp(3) DEFAULT NULL,
    completed_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (after_sale_no),
    CONSTRAINT chk_as_amount CHECK (amount >= 0)
);

CREATE INDEX idx_tx_after_sales_order_item ON tx_after_sales (order_item_id);
CREATE INDEX idx_tx_after_sales_merchant_status ON tx_after_sales (merchant_id, status);
CREATE INDEX idx_tx_after_sales_user_status ON tx_after_sales (user_id, status);

CREATE TRIGGER trg_tx_after_sales_updated_at
    BEFORE UPDATE ON tx_after_sales
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_after_sales IS '售后单表';
COMMENT ON COLUMN tx_after_sales.after_sale_no IS '售后单号';
COMMENT ON COLUMN tx_after_sales.order_id IS '订单ID';
COMMENT ON COLUMN tx_after_sales.order_item_id IS '订单明细ID';
COMMENT ON COLUMN tx_after_sales.merchant_id IS '商家ID';
COMMENT ON COLUMN tx_after_sales.user_id IS '用户ID';
COMMENT ON COLUMN tx_after_sales.after_sale_type IS 'refund-退款 return-退货 exchange-换货';
COMMENT ON COLUMN tx_after_sales.apply_quantity IS '申请售后数量';
COMMENT ON COLUMN tx_after_sales.reason IS '申请原因';
COMMENT ON COLUMN tx_after_sales.amount IS '退款金额（分）';
COMMENT ON COLUMN tx_after_sales.refund_id IS '关联退款单ID';
COMMENT ON COLUMN tx_after_sales.refund_no IS '关联退款单号';
COMMENT ON COLUMN tx_after_sales.status IS '0-待审核 1-审核通过(待退货) 2-退货中 3-待退款 4-已完成 5-已拒绝 6-已取消';
COMMENT ON COLUMN tx_after_sales.return_carrier IS '退货物流商';
COMMENT ON COLUMN tx_after_sales.return_tracking_no IS '退货运单号';
COMMENT ON COLUMN tx_after_sales.return_shipped_at IS '买家退货发出时间';
COMMENT ON COLUMN tx_after_sales.merchant_received_at IS '商家收货时间';
COMMENT ON COLUMN tx_after_sales.apply_at IS '申请时间';
COMMENT ON COLUMN tx_after_sales.audited_at IS '审核时间';
COMMENT ON COLUMN tx_after_sales.completed_at IS '完成时间';


CREATE TABLE tx_after_sale_evidences (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    after_sale_id bigint NOT NULL,
    media_type smallint NOT NULL DEFAULT 1,
    media_url varchar(500) NOT NULL,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tx_after_sale_evidences_sale ON tx_after_sale_evidences (after_sale_id);

COMMENT ON TABLE tx_after_sale_evidences IS '售后凭证表';
COMMENT ON COLUMN tx_after_sale_evidences.after_sale_id IS '售后单ID';
COMMENT ON COLUMN tx_after_sale_evidences.media_type IS '1-图片 2-视频';
COMMENT ON COLUMN tx_after_sale_evidences.media_url IS '凭证URL';
COMMENT ON COLUMN tx_after_sale_evidences.sort_order IS '排序';


CREATE TABLE tx_after_sale_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    after_sale_id bigint NOT NULL,
    operator_id bigint NOT NULL DEFAULT 0,
    operator_type varchar(20) NOT NULL DEFAULT 'system',
    action varchar(50) NOT NULL,
    remark varchar(500) DEFAULT '',
    created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tx_after_sale_logs_sale ON tx_after_sale_logs (after_sale_id);
CREATE INDEX idx_tx_after_sale_logs_created_at ON tx_after_sale_logs (created_at);

COMMENT ON TABLE tx_after_sale_logs IS '售后流程日志表';
COMMENT ON COLUMN tx_after_sale_logs.after_sale_id IS '售后单ID';
COMMENT ON COLUMN tx_after_sale_logs.operator_id IS '操作人ID';
COMMENT ON COLUMN tx_after_sale_logs.operator_type IS 'operator/user/merchant/admin';
COMMENT ON COLUMN tx_after_sale_logs.action IS '动作';
COMMENT ON COLUMN tx_after_sale_logs.remark IS '备注';
