-- ============================================================
-- tx_p4.sql — PostgreSQL
-- 物流配送表（依赖 P0: orders, P2: order_items）
-- ============================================================

CREATE TABLE tx_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_no varchar(32) NOT NULL,
    order_id bigint NOT NULL,
    order_no varchar(32) NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    carrier varchar(20) NOT NULL DEFAULT '',
    tracking_no varchar(64) NOT NULL DEFAULT '',
    warehouse_id bigint NOT NULL DEFAULT 0,
    package_count int NOT NULL DEFAULT 1,
    consignee varchar(64) NOT NULL DEFAULT '',
    phone varchar(20) NOT NULL DEFAULT '',
    province varchar(32) DEFAULT '',
    city varchar(32) DEFAULT '',
    district varchar(32) DEFAULT '',
    detail_addr varchar(256) DEFAULT '',
    shipping_fee bigint NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'pending',
    shipped_at timestamp(3) DEFAULT NULL,
    delivered_at timestamp(3) DEFAULT NULL,
    created_by bigint NOT NULL DEFAULT 0,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (delivery_no)
);

CREATE INDEX idx_tx_deliveries_order_id ON tx_deliveries (order_id);
CREATE INDEX idx_tx_deliveries_order_no ON tx_deliveries (order_no);
CREATE INDEX idx_tx_deliveries_merchant ON tx_deliveries (merchant_id);
CREATE INDEX idx_tx_deliveries_tracking ON tx_deliveries (tracking_no);
CREATE INDEX idx_tx_deliveries_status ON tx_deliveries (status);
CREATE INDEX idx_tx_deliveries_created_at ON tx_deliveries (created_at);

CREATE TRIGGER trg_tx_deliveries_updated_at
    BEFORE UPDATE ON tx_deliveries
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_deliveries IS '物流单主表（一个订单可拆多个物流单）';
COMMENT ON COLUMN tx_deliveries.delivery_no IS '物流单号（业务唯一）';
COMMENT ON COLUMN tx_deliveries.order_id IS '关联 tx_orders.id';
COMMENT ON COLUMN tx_deliveries.order_no IS '订单号（冗余）';
COMMENT ON COLUMN tx_deliveries.merchant_id IS '所属商家ID';
COMMENT ON COLUMN tx_deliveries.carrier IS '物流商：sf-顺丰 yto-圆通 zto-中通 yunda-韵达 jd-京东物流 other-其他';
COMMENT ON COLUMN tx_deliveries.tracking_no IS '运单号（物流商单号）';
COMMENT ON COLUMN tx_deliveries.warehouse_id IS '发货仓库ID';
COMMENT ON COLUMN tx_deliveries.package_count IS '包裹数量';
COMMENT ON COLUMN tx_deliveries.consignee IS '收货人';
COMMENT ON COLUMN tx_deliveries.phone IS '联系电话';
COMMENT ON COLUMN tx_deliveries.shipping_fee IS '运费（分）';
COMMENT ON COLUMN tx_deliveries.status IS '物流状态：pending-待发货 picked-已拣货 shipped-已发货 delivering-配送中 delivered-已签收 returned-已退回';
COMMENT ON COLUMN tx_deliveries.shipped_at IS '发货时间';
COMMENT ON COLUMN tx_deliveries.delivered_at IS '签收时间';
COMMENT ON COLUMN tx_deliveries.created_by IS '操作人ID';


CREATE TABLE tx_delivery_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    sku_id bigint NOT NULL DEFAULT 0,
    product_name varchar(200) DEFAULT '',
    quantity int NOT NULL DEFAULT 1,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_tx_delivery_items_delivery ON tx_delivery_items (delivery_id);
CREATE INDEX idx_tx_delivery_items_order_item ON tx_delivery_items (order_item_id);
CREATE INDEX idx_tx_delivery_items_sku ON tx_delivery_items (sku_id);

COMMENT ON TABLE tx_delivery_items IS '物流发货明细（订单项与包裹的映射）';
COMMENT ON COLUMN tx_delivery_items.delivery_id IS '关联 tx_deliveries.id';
COMMENT ON COLUMN tx_delivery_items.order_item_id IS '关联 tx_order_items.id';
COMMENT ON COLUMN tx_delivery_items.sku_id IS 'SKU ID（冗余）';
COMMENT ON COLUMN tx_delivery_items.product_name IS '商品名（冗余快照）';
COMMENT ON COLUMN tx_delivery_items.quantity IS '本次发货数量';


CREATE TABLE tx_delivery_traces (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_id bigint NOT NULL,
    tracking_no varchar(64) NOT NULL DEFAULT '',
    trace_time timestamp(3) NOT NULL,
    location varchar(200) DEFAULT '',
    status varchar(50) NOT NULL,
    description varchar(500) DEFAULT '',
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, trace_time)
);

CREATE INDEX idx_tx_delivery_traces_delivery ON tx_delivery_traces (delivery_id);
CREATE INDEX idx_tx_delivery_traces_tracking ON tx_delivery_traces (tracking_no);
CREATE INDEX idx_tx_delivery_traces_time ON tx_delivery_traces (trace_time);

COMMENT ON TABLE tx_delivery_traces IS '物流轨迹表（物流商回传的节点信息）';
COMMENT ON COLUMN tx_delivery_traces.delivery_id IS '关联 tx_deliveries.id';
COMMENT ON COLUMN tx_delivery_traces.tracking_no IS '运单号（冗余，方便直接查）';
COMMENT ON COLUMN tx_delivery_traces.trace_time IS '轨迹发生时间';
COMMENT ON COLUMN tx_delivery_traces.location IS '轨迹地点（如：深圳分拨中心）';
COMMENT ON COLUMN tx_delivery_traces.status IS '轨迹节点（如：已揽收、已到达分拨中心、派送中）';
COMMENT ON COLUMN tx_delivery_traces.description IS '轨迹描述（如：快件已到达深圳分拨中心）';
