-- ============================================================
-- tx_p2.sql — PostgreSQL
-- 支付退款相关表（依赖 P0: orders）
-- ============================================================

CREATE TABLE tx_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    payment_no varchar(32) NOT NULL,
    order_no varchar(32) NOT NULL,
    order_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    order_type varchar(20) NOT NULL DEFAULT 'order',
    amount bigint NOT NULL,
    currency varchar(10) NOT NULL DEFAULT 'CNY',
    payment_method varchar(32) NOT NULL,
    channel varchar(32) DEFAULT '',
    trade_type varchar(32) DEFAULT '',
    transaction_id varchar(128) DEFAULT NULL,
    idempotency_key varchar(64) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    failure_reason varchar(500) DEFAULT '',
    client_ip varchar(50) DEFAULT '',
    expire_at timestamp(3) DEFAULT NULL,
    paid_at timestamp(3) DEFAULT NULL,
    notify_at timestamp(3) DEFAULT NULL,
    channel_response jsonb DEFAULT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (payment_no),
    UNIQUE (idempotency_key),
    UNIQUE (transaction_id),
    CONSTRAINT chk_pay_amount_positive CHECK (amount > 0)
);

CREATE INDEX idx_tx_payments_order_no ON tx_payments (order_no);
CREATE INDEX idx_tx_payments_status_expire ON tx_payments (status, expire_at);

CREATE TRIGGER trg_tx_payments_updated_at
    BEFORE UPDATE ON tx_payments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_payments IS '支付单表';
COMMENT ON COLUMN tx_payments.payment_no IS '支付单号（业务唯一键）';
COMMENT ON COLUMN tx_payments.order_no IS '关联订单号';
COMMENT ON COLUMN tx_payments.order_id IS '关联 tx_orders.id';
COMMENT ON COLUMN tx_payments.merchant_id IS '所属商家ID';
COMMENT ON COLUMN tx_payments.order_type IS '订单类型：order-普通订单 flash-秒杀订单';
COMMENT ON COLUMN tx_payments.amount IS '支付金额（分）';
COMMENT ON COLUMN tx_payments.payment_method IS '支付方式：wechat-微信 alipay-支付宝 wallet-余额';
COMMENT ON COLUMN tx_payments.channel IS '支付渠道（如 wechat_native-微信 native alipay_page-支付宝页面）';
COMMENT ON COLUMN tx_payments.trade_type IS '交易类型：native-jsapi-app-h5-page';
COMMENT ON COLUMN tx_payments.transaction_id IS '支付渠道交易号（微信/支付宝订单号，用于对账）';
COMMENT ON COLUMN tx_payments.idempotency_key IS '支付创建幂等键（防重复提交）';
COMMENT ON COLUMN tx_payments.status IS '支付状态：pending-待支付 processing-处理中 success-已支付 failed-支付失败 refunding-退款中 refunded-已退款';
COMMENT ON COLUMN tx_payments.failure_reason IS '失败原因';
COMMENT ON COLUMN tx_payments.client_ip IS '客户端IP';
COMMENT ON COLUMN tx_payments.expire_at IS '支付过期时间';
COMMENT ON COLUMN tx_payments.paid_at IS '支付成功时间';
COMMENT ON COLUMN tx_payments.notify_at IS '最近一次渠道回调时间';
COMMENT ON COLUMN tx_payments.channel_response IS '渠道最近一次响应/回调摘要';


CREATE TABLE tx_payment_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    payment_id bigint NOT NULL,
    payment_no varchar(32) NOT NULL,
    channel varchar(32) DEFAULT '',
    transaction_id varchar(128) DEFAULT '',
    action varchar(30) NOT NULL,
    request_body text,
    response_body text,
    status varchar(20) DEFAULT '',
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_tx_payment_logs_payment_id ON tx_payment_logs (payment_id);
CREATE INDEX idx_tx_payment_logs_payment_no ON tx_payment_logs (payment_no);
CREATE INDEX idx_tx_payment_logs_transaction_id ON tx_payment_logs (transaction_id);
CREATE INDEX idx_tx_payment_logs_action ON tx_payment_logs (action);
CREATE INDEX idx_tx_payment_logs_created_at ON tx_payment_logs (created_at);

COMMENT ON TABLE tx_payment_logs IS '支付渠道通信日志（对账与排障）';
COMMENT ON COLUMN tx_payment_logs.payment_id IS '关联 tx_payments.id';
COMMENT ON COLUMN tx_payment_logs.payment_no IS '支付单号（冗余）';
COMMENT ON COLUMN tx_payment_logs.channel IS '支付渠道';
COMMENT ON COLUMN tx_payment_logs.transaction_id IS '渠道交易号';
COMMENT ON COLUMN tx_payment_logs.action IS '操作类型：create-创建 pay-支付回调 refund-退款 refund_callback-退款回调 close-关闭';
COMMENT ON COLUMN tx_payment_logs.request_body IS '请求参数（渠道原始数据，用于对账排查）';
COMMENT ON COLUMN tx_payment_logs.response_body IS '响应结果（渠道原始数据）';
COMMENT ON COLUMN tx_payment_logs.status IS '操作结果状态';


CREATE TABLE tx_refunds (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    refund_no varchar(32) NOT NULL,
    payment_id bigint NOT NULL,
    payment_no varchar(32) NOT NULL,
    order_no varchar(32) NOT NULL,
    order_id bigint NOT NULL,
    merchant_id bigint NOT NULL DEFAULT 0,
    amount bigint NOT NULL,
    reason varchar(500) DEFAULT '',
    status varchar(20) NOT NULL DEFAULT 'pending',
    channel_refund_id varchar(128) DEFAULT NULL,
    failure_reason varchar(500) DEFAULT '',
    channel_response jsonb DEFAULT NULL,
    idempotency_key varchar(64) NOT NULL,
    applied_at timestamp(3) DEFAULT NULL,
    success_at timestamp(3) DEFAULT NULL,
    notify_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (refund_no),
    UNIQUE (channel_refund_id),
    UNIQUE (idempotency_key),
    CONSTRAINT chk_refund_amount CHECK (amount > 0)
);

CREATE INDEX idx_tx_refunds_payment_no ON tx_refunds (payment_no);
CREATE INDEX idx_tx_refunds_order_no ON tx_refunds (order_no);

CREATE TRIGGER trg_tx_refunds_updated_at
    BEFORE UPDATE ON tx_refunds
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE tx_refunds IS '退款单表';
COMMENT ON COLUMN tx_refunds.refund_no IS '退款单号（业务唯一键）';
COMMENT ON COLUMN tx_refunds.payment_id IS '关联 tx_payments.id';
COMMENT ON COLUMN tx_refunds.payment_no IS '关联支付单号';
COMMENT ON COLUMN tx_refunds.order_no IS '关联订单号';
COMMENT ON COLUMN tx_refunds.order_id IS '关联 tx_orders.id';
COMMENT ON COLUMN tx_refunds.merchant_id IS '所属商家ID';
COMMENT ON COLUMN tx_refunds.amount IS '退款金额（分）';
COMMENT ON COLUMN tx_refunds.reason IS '退款原因';
COMMENT ON COLUMN tx_refunds.status IS '退款状态：pending-待处理 processing-处理中 success-已退款 failed-退款失败 rejected-已拒绝';
COMMENT ON COLUMN tx_refunds.channel_refund_id IS '渠道退款交易号';
COMMENT ON COLUMN tx_refunds.failure_reason IS '失败原因';
COMMENT ON COLUMN tx_refunds.channel_response IS '渠道退款响应/回调摘要';
COMMENT ON COLUMN tx_refunds.idempotency_key IS '退款幂等键';
COMMENT ON COLUMN tx_refunds.applied_at IS '申请时间';
COMMENT ON COLUMN tx_refunds.success_at IS '退款成功时间';
COMMENT ON COLUMN tx_refunds.notify_at IS '最近一次退款回调时间';
