-- ============================================================
-- usr_p0.sql — PostgreSQL
-- 用户域核心基础表
-- ============================================================

CREATE TABLE usr_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) DEFAULT NULL,
    password_hash varchar(255) NOT NULL DEFAULT '',
    email varchar(100) DEFAULT NULL,
    email_verified smallint NOT NULL DEFAULT 0,
    phone varchar(20) DEFAULT NULL,
    phone_verified smallint NOT NULL DEFAULT 0,
    avatar varchar(512) NOT NULL DEFAULT '',
    nickname varchar(50) NOT NULL DEFAULT '',
    status user_status NOT NULL DEFAULT 'active',
    register_ip varchar(50) NOT NULL DEFAULT '',
    register_source register_source NOT NULL DEFAULT 'web',
    last_login_ip varchar(50) NOT NULL DEFAULT '',
    last_login_at timestamp(3) DEFAULT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (username),
    UNIQUE (email),
    UNIQUE (phone)
);

-- 部分索引：只索引未删除记录
CREATE INDEX idx_usr_users_active ON usr_users (status, id)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_usr_users_status ON usr_users (status);

CREATE TRIGGER trg_usr_users_updated_at
    BEFORE UPDATE ON usr_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE usr_users IS '用户账户主表';
COMMENT ON COLUMN usr_users.username IS '用户名（唯一，NULL表示未设置）';
COMMENT ON COLUMN usr_users.password_hash IS 'bcrypt 密码哈希';
COMMENT ON COLUMN usr_users.email IS '邮箱（唯一，NULL表示未绑定）';
COMMENT ON COLUMN usr_users.email_verified IS '邮箱是否已验证';
COMMENT ON COLUMN usr_users.phone IS '手机号（唯一，NULL表示未绑定）';
COMMENT ON COLUMN usr_users.phone_verified IS '手机号是否已验证';
COMMENT ON COLUMN usr_users.avatar IS '头像URL';
COMMENT ON COLUMN usr_users.nickname IS '昵称';
COMMENT ON COLUMN usr_users.status IS '状态：active-正常 disabled-禁用 frozen-冻结';
COMMENT ON COLUMN usr_users.register_ip IS '注册IP';
COMMENT ON COLUMN usr_users.register_source IS '注册来源：web/ios/android/admin';
COMMENT ON COLUMN usr_users.last_login_ip IS '最后登录IP';
COMMENT ON COLUMN usr_users.last_login_at IS '最后登录时间';


CREATE TABLE usr_infos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    gender gender NOT NULL DEFAULT 'unknown',
    birthday date DEFAULT NULL,
    bio varchar(200) NOT NULL DEFAULT '',
    country varchar(32) NOT NULL DEFAULT '',
    province varchar(32) NOT NULL DEFAULT '',
    city varchar(32) NOT NULL DEFAULT '',
    zip_code varchar(10) NOT NULL DEFAULT '',
    language varchar(10) NOT NULL DEFAULT 'zh-CN',
    timezone varchar(32) NOT NULL DEFAULT 'Asia/Shanghai',
    level_id bigint NOT NULL DEFAULT 0,
    total_points bigint NOT NULL DEFAULT 0,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id)
);

CREATE INDEX idx_usr_infos_active ON usr_infos (user_id)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_usr_infos_updated_at
    BEFORE UPDATE ON usr_infos
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE usr_infos IS '用户扩展信息表';
COMMENT ON COLUMN usr_infos.gender IS '性别：unknown-未知 male-男 female-女';
COMMENT ON COLUMN usr_infos.birthday IS '生日';
COMMENT ON COLUMN usr_infos.bio IS '个人简介';
COMMENT ON COLUMN usr_infos.country IS '国家';
COMMENT ON COLUMN usr_infos.province IS '省';
COMMENT ON COLUMN usr_infos.city IS '市';
COMMENT ON COLUMN usr_infos.zip_code IS '邮编';
COMMENT ON COLUMN usr_infos.language IS '语言';
COMMENT ON COLUMN usr_infos.timezone IS '时区';
COMMENT ON COLUMN usr_infos.level_id IS '当前等级ID（关联 usr_levels.id）';
COMMENT ON COLUMN usr_infos.total_points IS '累计积分';


CREATE TABLE usr_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    consignee varchar(64) NOT NULL DEFAULT '',
    phone varchar(20) NOT NULL DEFAULT '',
    country varchar(32) NOT NULL DEFAULT '',
    province varchar(32) NOT NULL DEFAULT '',
    city varchar(32) NOT NULL DEFAULT '',
    district varchar(32) NOT NULL DEFAULT '',
    detail varchar(256) NOT NULL DEFAULT '',
    zip_code varchar(10) NOT NULL DEFAULT '',
    tag address_tag NOT NULL DEFAULT 'home',
    is_default smallint DEFAULT NULL,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, is_default)
);

CREATE INDEX idx_usr_addresses_active ON usr_addresses (user_id)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_usr_addresses_updated_at
    BEFORE UPDATE ON usr_addresses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE usr_addresses IS '用户收货地址';
COMMENT ON COLUMN usr_addresses.consignee IS '收货人姓名';
COMMENT ON COLUMN usr_addresses.phone IS '联系电话';
COMMENT ON COLUMN usr_addresses.country IS '国家';
COMMENT ON COLUMN usr_addresses.province IS '省';
COMMENT ON COLUMN usr_addresses.city IS '市';
COMMENT ON COLUMN usr_addresses.district IS '区/县';
COMMENT ON COLUMN usr_addresses.detail IS '详细地址';
COMMENT ON COLUMN usr_addresses.zip_code IS '邮编';
COMMENT ON COLUMN usr_addresses.tag IS '地址标签：home/office/company/other';
COMMENT ON COLUMN usr_addresses.is_default IS '是否默认地址（NULL=非默认, 1=默认）';


CREATE TABLE usr_login_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    login_ip varchar(50) NOT NULL DEFAULT '',
    login_device varchar(100) NOT NULL DEFAULT '',
    login_location varchar(100) NOT NULL DEFAULT '',
    login_method login_method NOT NULL DEFAULT 'password',
    login_status smallint NOT NULL DEFAULT 1,
    failure_reason varchar(100) NOT NULL DEFAULT '',
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_usr_login_histories_user_id ON usr_login_histories (user_id);
CREATE INDEX idx_usr_login_histories_time_brin ON usr_login_histories USING BRIN (created_at)
    WITH (pages_per_range = 32);

COMMENT ON TABLE usr_login_histories IS 'C端消费者登录历史表';
COMMENT ON COLUMN usr_login_histories.login_ip IS '登录IP';
COMMENT ON COLUMN usr_login_histories.login_device IS '登录设备信息（UA）';
COMMENT ON COLUMN usr_login_histories.login_location IS '登录地点';
COMMENT ON COLUMN usr_login_histories.login_method IS '登录方式：password/sms/oauth';
COMMENT ON COLUMN usr_login_histories.login_status IS '登录结果：1-成功 0-失败';
COMMENT ON COLUMN usr_login_histories.failure_reason IS '失败原因';
