-- ============================================================
-- usr_p1.sql — PostgreSQL
-- 用户等级与积分体系（依赖 P0: usr_users）
-- ============================================================

CREATE TABLE usr_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    level int NOT NULL,
    icon varchar(255) NOT NULL DEFAULT '',
    min_points bigint NOT NULL DEFAULT 0,
    discount_rate bigint NOT NULL DEFAULT 100,
    free_shipping smallint NOT NULL DEFAULT 0,
    points_multiplier decimal(3,2) NOT NULL DEFAULT 1.00,
    benefits jsonb DEFAULT NULL,
    status smallint NOT NULL DEFAULT 1,
    sort_order int NOT NULL DEFAULT 0,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (level)
);

CREATE INDEX idx_usr_levels_status ON usr_levels (status);
CREATE INDEX idx_usr_levels_deleted_at ON usr_levels (deleted_at);

CREATE TRIGGER trg_usr_levels_updated_at
    BEFORE UPDATE ON usr_levels
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE usr_levels IS '用户等级定义表';
COMMENT ON COLUMN usr_levels.name IS '等级名称（如：青铜会员、白银会员、黄金会员、钻石会员）';
COMMENT ON COLUMN usr_levels.level IS '等级数值（1=青铜 2=白银 3=黄金 4=钻石）';
COMMENT ON COLUMN usr_levels.icon IS '等级图标URL';
COMMENT ON COLUMN usr_levels.min_points IS '该等级所需最低累计积分';
COMMENT ON COLUMN usr_levels.discount_rate IS '折扣率（千分比，1000=无折扣，900=九折）';
COMMENT ON COLUMN usr_levels.free_shipping IS '1-免运费';
COMMENT ON COLUMN usr_levels.points_multiplier IS '消费积分倍数（如 1.5 倍积分）';
COMMENT ON COLUMN usr_levels.benefits IS '扩展权益JSON（如：{"birthday_gift": true, "exclusive_coupon": true}）';
COMMENT ON COLUMN usr_levels.status IS '1-启用 0-禁用';
COMMENT ON COLUMN usr_levels.sort_order IS '排序';


CREATE TABLE usr_level_rules (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL DEFAULT '',
    rule_type varchar(20) NOT NULL DEFAULT '',
    from_level_id bigint NOT NULL DEFAULT 0,
    to_level_id bigint NOT NULL DEFAULT 0,
    condition_type varchar(50) NOT NULL DEFAULT '',
    condition_value bigint NOT NULL DEFAULT 0,
    description text,
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TRIGGER trg_usr_level_rules_updated_at
    BEFORE UPDATE ON usr_level_rules
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE usr_level_rules IS '等级升降级规则配置';
COMMENT ON COLUMN usr_level_rules.name IS '规则名称';
COMMENT ON COLUMN usr_level_rules.rule_type IS '规则类型：upgrade-自动升级 downgrade-自动降级';
COMMENT ON COLUMN usr_level_rules.from_level_id IS '源等级ID（0=任意等级）';
COMMENT ON COLUMN usr_level_rules.to_level_id IS '目标等级ID';
COMMENT ON COLUMN usr_level_rules.condition_type IS '条件类型：points-累计积分 order_count-订单数 order_amount-消费金额';
COMMENT ON COLUMN usr_level_rules.condition_value IS '条件阈值';
COMMENT ON COLUMN usr_level_rules.description IS '规则说明';
COMMENT ON COLUMN usr_level_rules.sort_order IS '排序';
COMMENT ON COLUMN usr_level_rules.status IS '状态：0-禁用 1-启用';


CREATE TABLE usr_points (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    points bigint NOT NULL,
    balance_after bigint NOT NULL DEFAULT 0,
    source varchar(30) NOT NULL,
    source_id varchar(64) DEFAULT '',
    expire_at timestamp(3) DEFAULT NULL,
    status smallint NOT NULL DEFAULT 0,
    remark varchar(200) DEFAULT '',
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_usr_points_user_id ON usr_points (user_id);
CREATE INDEX idx_usr_points_source ON usr_points (source, source_id);
CREATE INDEX idx_usr_points_expire_at ON usr_points (expire_at);
CREATE INDEX idx_usr_points_created_at ON usr_points (created_at);

COMMENT ON TABLE usr_points IS '用户积分流水表';
COMMENT ON COLUMN usr_points.user_id IS '用户ID';
COMMENT ON COLUMN usr_points.points IS '积分变动（正=增加，负=扣减）';
COMMENT ON COLUMN usr_points.balance_after IS '变动后积分余额';
COMMENT ON COLUMN usr_points.source IS '积分来源：order-下单消费 review-评价 signin-签到 admin-管理员调整 refund-退款扣减 expire-过期清零';
COMMENT ON COLUMN usr_points.source_id IS '来源ID（如订单号、评价ID）';
COMMENT ON COLUMN usr_points.expire_at IS '过期时间（NULL=永不过期）';
COMMENT ON COLUMN usr_points.status IS '0-待确认 1-已确认 2-已过期 3-已作废';
COMMENT ON COLUMN usr_points.remark IS '备注';


CREATE TABLE usr_points_rules (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL DEFAULT '',
    rule_key varchar(50) NOT NULL DEFAULT '',
    value_int int DEFAULT NULL,
    value_decimal decimal(10,2) DEFAULT NULL,
    value_string varchar(255) DEFAULT '',
    description text,
    sort_order int NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (rule_key)
);

CREATE TRIGGER trg_usr_points_rules_updated_at
    BEFORE UPDATE ON usr_points_rules
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE usr_points_rules IS '积分规则配置';
COMMENT ON COLUMN usr_points_rules.name IS '规则名称';
COMMENT ON COLUMN usr_points_rules.rule_key IS '规则键名：earn_rate-消费返积分比例 expire_days-积分过期天数 signin_points-签到奖励积分 review_points-评价奖励积分';
COMMENT ON COLUMN usr_points_rules.value_int IS '整数值（如积分数量、天数）';
COMMENT ON COLUMN usr_points_rules.value_decimal IS '小数值（如比例、倍数）';
COMMENT ON COLUMN usr_points_rules.value_string IS '字符串值（如配置json、文本）';
COMMENT ON COLUMN usr_points_rules.description IS '规则说明';
COMMENT ON COLUMN usr_points_rules.sort_order IS '排序';
COMMENT ON COLUMN usr_points_rules.status IS '状态：0-禁用 1-启用';
